### ISSUE TITLE
Limit available disk space for backup?

### ISSUE THREAD

**Issue by morpheus65535** [mbentley/docker-timemachine#1]
Is there a way to limit the space that could be use by timemachine backup so it doesn't fill my disk?

Thanks!

**Comment by mbentley** [comment]
I would have to look into how this could be set but it looks like there might be some promising options documented here:  http://netatalk.sourceforge.net/2.1/htmldocs/AppleVolumes.default.5.html

See `volsizelimit`.  Not really sure where those might be set regarding the Time Machine backup but it is a place to look.

**Comment by morpheus65535** [comment]
In ```afp.conf```, you need to add this inside [TimeMachine] share:

```
# the max size of the data folder (in Mb)
vol size limit = 512000
```

Maybe you could read this from an ENV variable?

**Comment by mbentley** [comment]
Yeah, that should be pretty easy.  Would just have to write the config as a part of the entrypoint script.

**Comment by mbentley** [comment]
OK, looks like it works as expected.  Thanks for tracking that down.  Once the autobuild completes on Docker Hub, it should be available.  Otherwise, there is a test image at `mbentley/timemachine:test`.
