### ISSUE TITLE
timemachine is not using dedicated volume

### ISSUE THREAD

**Issue by Buzz2912** [mbentley/docker-timemachine#103]
Hi,

I just installed your Time Machine container through docker hub.

I specified 
-v /timemachine:/opt/timemachine

/timemachine on the host is a bind mount in a LXC Container

The TM-Backup is not written to that folder, it is written to somewhere else and fills the disk of the docker host.

Just to check I did the same with a different container from docker hub: default50/timemachinesambadocker

Here it works as expected.

Thanks Sebastian

**Comment by mbentley** [comment]
Without further details about how you're running the container, it's difficult to say why it wouldn't be working but I know it's working correctly by default.  Are you specifying additional configuration to not use the default `timemachine` user?  Where is it writing data to inside of the container?

**Comment by Buzz2912** [comment]
I did change user and password but nothing else.

Just tried again with standard user and password and now it works. Very strange..

Thanks Sebastian

**Comment by mbentley** [comment]
If you change the username, it changes the path.  It's going to write data to `/opt/<username>`.
