### ISSUE TITLE
Submit to DockSTARTer

### ISSUE THREAD

**Issue by samAheenan** [mbentley/docker-timemachine#118]
As per the [feature request](https://github.com/GhostWriters/DockSTARTer/issues/1344) submitted at DockSTARter's GitHub, I think that this container would be a great addition to their suite. They accept Pull Requests for container submissions so I thought I would come straight to the source to request it.

**Is your feature request related to a problem? Please describe.**
No problem - just a suggestion. I currently have a separate VM for Time Machine only and would love to see it be part of DockSTARter so I keep all my home lab stuff on the same Docker-specific VM.

**Describe the solution you'd like**
Submitting this container to the DockSTARter project by using a Pull Request on [their GitHub](https://github.com/GhostWriters/DockSTARTer/compare).

**Additional context**
I am adequate at implementing solutions that other people have created but am sadly inadequate at creating those solutions myself which is why I am requesting it rather than just doing it myself! Ideally it would benefit people other than me as well though.

**Comment by mbentley** [comment]
Interesting - had never heard of DockSTARTer before.  Not sure if I have the spare time at the moment to contribute to that and "support" it but funny enough, someone has contributed another one of my packaged images to it ([omada-controller](https://github.com/GhostWriters/DockSTARTer/blob/1fdd771ec36c62668b4d6bac9c6aa9d244e335e1/docs/apps/omadacontroller.md)).

**Comment by samAheenan** [comment]
Thanks for your reply, Matt.

**Comment by mbentley** [comment]
No worries.  If I get the time, I'll consider adding my time machine image if I get a chance to figure out the format; didn't look terrible, just figuring out exactly what is needed to convert the [existing compose](https://github.com/mbentley/docker-timemachine/blob/master/timemachine-compose-smb.yml) file into the required format.

**Comment by mbentley** [comment]
Looks like it is going to be added; closing.

**Comment by samAheenan** [comment]
I watched the progress on that ticket with excitement. Thanks again!
