### ISSUE TITLE
Hostname conflict, keeps retrying to register

### ISSUE THREAD

**Issue by vhaasteren** [mbentley/docker-timemachine#119]
I have this issue with my timemachine docker. It's worked well in the past half year or so. I usually never touch it, but at the moment I can't get the server to launch. Somehow, it thinks there is a hostname conflict. Not sure whether this is the server os (still on Ubuntu 20.04), the network controller (Unifi Cloud Key G2+), or the docker container (mbentley/timemachine:smb), but both my macbook (M1 max on 12.5 and mbpro on 10.15.7) cannot connect. The docker-compose is below, and below that is the relevant docker logs output.

I figure it has something to do with multiplex DNS, but I can't figure out exactly what to do.

    ## ----------------------------------------
    ## TIME MACHINE
    ## Time machine backup server on Lucy
    ## ----------------------------------------
    timemachine:
        image: mbentley/timemachine:smb
        container_name: timemachine
        hostname: lucy-timemachine
        restart: unless-stopped
        volumes:
            - '${TIME_MACHINE_PATH}:/opt/${TM_USERNAME}'
            - timemachine-netatalk:/var/netatalk
            - timemachine-logs:/var/log/supervisor
            - timemachine-var-lib-samba:/var/lib/samba
            - timemachine-var-cache-samba:/var/cache/samba
            - timemachine-run-samba:/run/samba
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "445:445"
        environment:
            - CUSTOM_SMB_CONF=false
            - CUSTOM_USER=false
            - DEBUG_LEVEL=1
            - EXTERNAL_CONF=
            - MIMIC_MODEL=TimeCapsule8,119
            - TM_USERNAME=${TM_USERNAME}
            - TM_GROUPNAME=${TM_GROUPNAME}
            - TM_UID=${TM_UID}
            - TM_GID=${TM_GID}
            - PASSWORD=${TM_PASSWORD}
            - SET_PERMISSIONS=true
            - VOLUME_SIZE_LIMIT=${VOLUME_SIZE_LIMIT}
            - SHARE_NAME=${SHARE_NAME}
            - SMB_INHERIT_PERMISSIONS=no
            - SMB_NFS_ACES=yes
            - SMB_METADATA=stream
            - SMB_PORT=445
            - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
            - HIDE_SHARES=no
            - WORKGROUP=WORKGROUP
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        network_mode: "host"

Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/smbd.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface veth3bee38d.IPv6 with address fe80::6846:e9ff:fe07:2b79.
New relevant interface veth3bee38d.IPv6 for mDNS.
Joining mDNS multicast group on interface veth21bf53a.IPv6 with address fe80::2448:60ff:fee5:cb32.
New relevant interface veth21bf53a.IPv6 for mDNS.
Joining mDNS multicast group on interface vethe2ca1fa.IPv6 with address fe80::d06c:e7ff:fe9c:55f5.
New relevant interface vethe2ca1fa.IPv6 for mDNS.
Joining mDNS multicast group on interface veth98d62c8.IPv6 with address fe80::a033:2aff:fe46:8a06.
New relevant interface veth98d62c8.IPv6 for mDNS.
Joining mDNS multicast group on interface vethc64d769.IPv6 with address fe80::68df:37ff:fe58:975e.
New relevant interface vethc64d769.IPv6 for mDNS.
Joining mDNS multicast group on interface veth7d9447f.IPv6 with address fe80::ec05:eff:fe9d:75bb.
New relevant interface veth7d9447f.IPv6 for mDNS.
Joining mDNS multicast group on interface vethda9432f.IPv6 with address fe80::acd2:adff:fe7f:a806.
New relevant interface vethda9432f.IPv6 for mDNS.
Joining mDNS multicast group on interface veth74b074f.IPv6 with address fe80::f81a:35ff:fe2d:da4d.
New relevant interface veth74b074f.IPv6 for mDNS.
Joining mDNS multicast group on interface vethc06d52f.IPv6 with address fe80::b4db:92ff:fe40:730b.
New relevant interface vethc06d52f.IPv6 for mDNS.
Joining mDNS multicast group on interface vethc9c79d1.IPv6 with address fe80::3cac:64ff:fea1:1ad5.
New relevant interface vethc9c79d1.IPv6 for mDNS.
Joining mDNS multicast group on interface veth7a70b29.IPv6 with address fe80::9406:10ff:feb8:b1cf.
New relevant interface veth7a70b29.IPv6 for mDNS.
Joining mDNS multicast group on interface veth920a57e.IPv6 with address fe80::cf6:f6ff:fe09:206e.
New relevant interface veth920a57e.IPv6 for mDNS.
Joining mDNS multicast group on interface veth9cfac2a.IPv6 with address fe80::1442:76ff:fe6d:1e60.
New relevant interface veth9cfac2a.IPv6 for mDNS.
Joining mDNS multicast group on interface veth9739fa3.IPv6 with address fe80::f8fb:75ff:feff:4fae.
New relevant interface veth9739fa3.IPv6 for mDNS.
Joining mDNS multicast group on interface veth05b0a51.IPv6 with address fe80::982b:fbff:fe41:196c.
New relevant interface veth05b0a51.IPv6 for mDNS.
Joining mDNS multicast group on interface veth77e4f7e.IPv6 with address fe80::b8a8:e6ff:feb2:efba.
New relevant interface veth77e4f7e.IPv6 for mDNS.
Joining mDNS multicast group on interface veth76bfad9.IPv6 with address fe80::78b3:91ff:fe49:739e.
New relevant interface veth76bfad9.IPv6 for mDNS.
Joining mDNS multicast group on interface veth24ea4d6.IPv6 with address fe80::24d5:49ff:fe32:2a4f.
New relevant interface veth24ea4d6.IPv6 for mDNS.
Joining mDNS multicast group on interface vetha3eaf9f.IPv6 with address fe80::186e:80ff:fe27:ba5c.
New relevant interface vetha3eaf9f.IPv6 for mDNS.
Joining mDNS multicast group on interface veth9f19510.IPv6 with address fe80::28f3:9fff:fec9:fd19.
New relevant interface veth9f19510.IPv6 for mDNS.
Joining mDNS multicast group on interface vethfc4c418.IPv6 with address fe80::cc08:50ff:fe4a:c704.
New relevant interface vethfc4c418.IPv6 for mDNS.
Joining mDNS multicast group on interface vethffd7332.IPv6 with address fe80::4a1:c3ff:fefd:9e71.
New relevant interface vethffd7332.IPv6 for mDNS.
Joining mDNS multicast group on interface veth4692833.IPv6 with address fe80::1838:37ff:feaa:faa0.
New relevant interface veth4692833.IPv6 for mDNS.
Joining mDNS multicast group on interface veth32428e1.IPv6 with address fe80::181f:3eff:fe95:6fb8.
New relevant interface veth32428e1.IPv6 for mDNS.
Joining mDNS multicast group on interface veth9f8e81a.IPv6 with address fe80::5c66:9bff:fe47:cc46.
New relevant interface veth9f8e81a.IPv6 for mDNS.
Joining mDNS multicast group on interface veth5d88477.IPv6 with address fe80::6828:42ff:fee8:462.
New relevant interface veth5d88477.IPv6 for mDNS.
Joining mDNS multicast group on interface veth501f12c.IPv6 with address fe80::c63:40ff:fe55:b03e.
New relevant interface veth501f12c.IPv6 for mDNS.
Joining mDNS multicast group on interface veth6e094eb.IPv6 with address fe80::8c68:a6ff:fe74:480c.
New relevant interface veth6e094eb.IPv6 for mDNS.
Joining mDNS multicast group on interface veth0d7dbfd.IPv6 with address fe80::cc6a:9ff:fef7:c3bb.
New relevant interface veth0d7dbfd.IPv6 for mDNS.
Joining mDNS multicast group on interface br-c557176ba5db.IPv6 with address fe80::42:eeff:fe45:848b.
New relevant interface br-c557176ba5db.IPv6 for mDNS.
Joining mDNS multicast group on interface br-c557176ba5db.IPv4 with address 172.20.0.1.
New relevant interface br-c557176ba5db.IPv4 for mDNS.
Joining mDNS multicast group on interface br-75f239d52eba.IPv6 with address fe80::42:dcff:fe33:1eb7.
New relevant interface br-75f239d52eba.IPv6 for mDNS.
Joining mDNS multicast group on interface br-75f239d52eba.IPv4 with address 172.27.0.1.
New relevant interface br-75f239d52eba.IPv4 for mDNS.
Joining mDNS multicast group on interface br-30d9e6417e2c.IPv6 with address fe80::42:ecff:feb2:2f57.
New relevant interface br-30d9e6417e2c.IPv6 for mDNS.
Joining mDNS multicast group on interface br-30d9e6417e2c.IPv4 with address 172.21.0.1.
New relevant interface br-30d9e6417e2c.IPv4 for mDNS.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface br-4ef159e28a8a.IPv6 with address fe80::42:2eff:fe9c:1eee.
New relevant interface br-4ef159e28a8a.IPv6 for mDNS.
Joining mDNS multicast group on interface br-4ef159e28a8a.IPv4 with address 172.23.0.1.
New relevant interface br-4ef159e28a8a.IPv4 for mDNS.
Joining mDNS multicast group on interface br-366a3f5dd6ee.IPv6 with address fe80::42:78ff:fe84:400f.
New relevant interface br-366a3f5dd6ee.IPv6 for mDNS.
Joining mDNS multicast group on interface br-366a3f5dd6ee.IPv4 with address 172.18.0.1.
New relevant interface br-366a3f5dd6ee.IPv4 for mDNS.
Joining mDNS multicast group on interface br-ce53aa0024a6.IPv6 with address fe80::42:39ff:fe16:6018.
New relevant interface br-ce53aa0024a6.IPv6 for mDNS.
Joining mDNS multicast group on interface br-ce53aa0024a6.IPv4 with address 192.168.99.1.
New relevant interface br-ce53aa0024a6.IPv4 for mDNS.
Joining mDNS multicast group on interface br-bc5eed1519f2.IPv6 with address fe80::42:3fff:fef2:bf99.
New relevant interface br-bc5eed1519f2.IPv6 for mDNS.
Joining mDNS multicast group on interface br-bc5eed1519f2.IPv4 with address 172.19.0.1.
New relevant interface br-bc5eed1519f2.IPv4 for mDNS.
Joining mDNS multicast group on interface br-abcfb14d7511.IPv6 with address fe80::42:59ff:fe02:7d19.
New relevant interface br-abcfb14d7511.IPv6 for mDNS.
Joining mDNS multicast group on interface br-abcfb14d7511.IPv4 with address 192.168.16.1.
New relevant interface br-abcfb14d7511.IPv4 for mDNS.
Joining mDNS multicast group on interface br-757af210df57.IPv6 with address fe80::42:9aff:fefb:9d36.
New relevant interface br-757af210df57.IPv6 for mDNS.
Joining mDNS multicast group on interface br-757af210df57.IPv4 with address 172.30.0.1.
New relevant interface br-757af210df57.IPv4 for mDNS.
Joining mDNS multicast group on interface eno1.IPv6 with address fe80::c234:fcc:96d3:4cec.
New relevant interface eno1.IPv6 for mDNS.
Joining mDNS multicast group on interface eno1.IPv4 with address 192.168.1.8.
New relevant interface eno1.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::6846:e9ff:fe07:2b79 on veth3bee38d.*.
Registering new address record for fe80::2448:60ff:fee5:cb32 on veth21bf53a.*.
Registering new address record for fe80::d06c:e7ff:fe9c:55f5 on vethe2ca1fa.*.
Registering new address record for fe80::a033:2aff:fe46:8a06 on veth98d62c8.*.
Registering new address record for fe80::68df:37ff:fe58:975e on vethc64d769.*.
Registering new address record for fe80::ec05:eff:fe9d:75bb on veth7d9447f.*.
Registering new address record for fe80::acd2:adff:fe7f:a806 on vethda9432f.*.
Registering new address record for fe80::f81a:35ff:fe2d:da4d on veth74b074f.*.
Registering new address record for fe80::b4db:92ff:fe40:730b on vethc06d52f.*.
Registering new address record for fe80::3cac:64ff:fea1:1ad5 on vethc9c79d1.*.
Registering new address record for fe80::9406:10ff:feb8:b1cf on veth7a70b29.*.
Registering new address record for fe80::cf6:f6ff:fe09:206e on veth920a57e.*.
Registering new address record for fe80::1442:76ff:fe6d:1e60 on veth9cfac2a.*.
Registering new address record for fe80::f8fb:75ff:feff:4fae on veth9739fa3.*.
Registering new address record for fe80::982b:fbff:fe41:196c on veth05b0a51.*.
Registering new address record for fe80::b8a8:e6ff:feb2:efba on veth77e4f7e.*.
Registering new address record for fe80::78b3:91ff:fe49:739e on veth76bfad9.*.
Registering new address record for fe80::24d5:49ff:fe32:2a4f on veth24ea4d6.*.
Registering new address record for fe80::186e:80ff:fe27:ba5c on vetha3eaf9f.*.
Registering new address record for fe80::28f3:9fff:fec9:fd19 on veth9f19510.*.
Registering new address record for fe80::cc08:50ff:fe4a:c704 on vethfc4c418.*.
Registering new address record for fe80::4a1:c3ff:fefd:9e71 on vethffd7332.*.
Registering new address record for fe80::1838:37ff:feaa:faa0 on veth4692833.*.
Registering new address record for fe80::181f:3eff:fe95:6fb8 on veth32428e1.*.
Registering new address record for fe80::5c66:9bff:fe47:cc46 on veth9f8e81a.*.
Registering new address record for fe80::6828:42ff:fee8:462 on veth5d88477.*.
Registering new address record for fe80::c63:40ff:fe55:b03e on veth501f12c.*.
Registering new address record for fe80::8c68:a6ff:fe74:480c on veth6e094eb.*.
Registering new address record for fe80::cc6a:9ff:fef7:c3bb on veth0d7dbfd.*.
Registering new address record for fe80::42:eeff:fe45:848b on br-c557176ba5db.*.
Registering new address record for 172.20.0.1 on br-c557176ba5db.IPv4.
Registering new address record for fe80::42:dcff:fe33:1eb7 on br-75f239d52eba.*.
Registering new address record for 172.27.0.1 on br-75f239d52eba.IPv4.
Registering new address record for fe80::42:ecff:feb2:2f57 on br-30d9e6417e2c.*.
Registering new address record for 172.21.0.1 on br-30d9e6417e2c.IPv4.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::42:2eff:fe9c:1eee on br-4ef159e28a8a.*.
Registering new address record for 172.23.0.1 on br-4ef159e28a8a.IPv4.
Registering new address record for fe80::42:78ff:fe84:400f on br-366a3f5dd6ee.*.
Registering new address record for 172.18.0.1 on br-366a3f5dd6ee.IPv4.
Registering new address record for fe80::42:39ff:fe16:6018 on br-ce53aa0024a6.*.
Registering new address record for 192.168.99.1 on br-ce53aa0024a6.IPv4.
Registering new address record for fe80::42:3fff:fef2:bf99 on br-bc5eed1519f2.*.
Registering new address record for 172.19.0.1 on br-bc5eed1519f2.IPv4.
Registering new address record for fe80::42:59ff:fe02:7d19 on br-abcfb14d7511.*.
Registering new address record for 192.168.16.1 on br-abcfb14d7511.IPv4.
Registering new address record for fe80::42:9aff:fefb:9d36 on br-757af210df57.*.
Registering new address record for 172.30.0.1 on br-757af210df57.IPv4.
Registering new address record for fe80::c234:fcc:96d3:4cec on eno1.*.
Registering new address record for 192.168.1.8 on eno1.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Withdrawing address record for fe80::2448:60ff:fee5:cb32 on veth21bf53a.
Withdrawing address record for fe80::d06c:e7ff:fe9c:55f5 on vethe2ca1fa.
Withdrawing address record for fe80::a033:2aff:fe46:8a06 on veth98d62c8.
Withdrawing address record for fe80::68df:37ff:fe58:975e on vethc64d769.
Withdrawing address record for fe80::ec05:eff:fe9d:75bb on veth7d9447f.
Withdrawing address record for fe80::acd2:adff:fe7f:a806 on vethda9432f.
Withdrawing address record for fe80::f81a:35ff:fe2d:da4d on veth74b074f.
Withdrawing address record for fe80::b4db:92ff:fe40:730b on vethc06d52f.
Withdrawing address record for fe80::3cac:64ff:fea1:1ad5 on vethc9c79d1.
Withdrawing address record for fe80::9406:10ff:feb8:b1cf on veth7a70b29.
Withdrawing address record for fe80::cf6:f6ff:fe09:206e on veth920a57e.
Withdrawing address record for fe80::1442:76ff:fe6d:1e60 on veth9cfac2a.
Withdrawing address record for fe80::f8fb:75ff:feff:4fae on veth9739fa3.
Withdrawing address record for fe80::982b:fbff:fe41:196c on veth05b0a51.
Withdrawing address record for fe80::b8a8:e6ff:feb2:efba on veth77e4f7e.
Withdrawing address record for fe80::78b3:91ff:fe49:739e on veth76bfad9.
Withdrawing address record for fe80::24d5:49ff:fe32:2a4f on veth24ea4d6.
Withdrawing address record for fe80::186e:80ff:fe27:ba5c on vetha3eaf9f.
Withdrawing address record for fe80::28f3:9fff:fec9:fd19 on veth9f19510.
Withdrawing address record for fe80::cc08:50ff:fe4a:c704 on vethfc4c418.
Withdrawing address record for fe80::4a1:c3ff:fefd:9e71 on vethffd7332.
Withdrawing address record for fe80::1838:37ff:feaa:faa0 on veth4692833.
Withdrawing address record for fe80::181f:3eff:fe95:6fb8 on veth32428e1.
Withdrawing address record for fe80::5c66:9bff:fe47:cc46 on veth9f8e81a.
Withdrawing address record for fe80::6828:42ff:fee8:462 on veth5d88477.
Withdrawing address record for fe80::c63:40ff:fe55:b03e on veth501f12c.
Withdrawing address record for fe80::8c68:a6ff:fe74:480c on veth6e094eb.
Withdrawing address record for fe80::cc6a:9ff:fef7:c3bb on veth0d7dbfd.
Withdrawing address record for fe80::42:eeff:fe45:848b on br-c557176ba5db.
Withdrawing address record for 172.20.0.1 on br-c557176ba5db.
Withdrawing address record for fe80::42:dcff:fe33:1eb7 on br-75f239d52eba.
Withdrawing address record for 172.27.0.1 on br-75f239d52eba.
Withdrawing address record for fe80::42:ecff:feb2:2f57 on br-30d9e6417e2c.
Withdrawing address record for 172.21.0.1 on br-30d9e6417e2c.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for fe80::42:2eff:fe9c:1eee on br-4ef159e28a8a.
Withdrawing address record for 172.23.0.1 on br-4ef159e28a8a.
Withdrawing address record for fe80::42:78ff:fe84:400f on br-366a3f5dd6ee.
Withdrawing address record for 172.18.0.1 on br-366a3f5dd6ee.
Withdrawing address record for fe80::42:39ff:fe16:6018 on br-ce53aa0024a6.
Withdrawing address record for 192.168.99.1 on br-ce53aa0024a6.
Withdrawing address record for fe80::42:3fff:fef2:bf99 on br-bc5eed1519f2.
Withdrawing address record for 172.19.0.1 on br-bc5eed1519f2.
Withdrawing address record for fe80::42:59ff:fe02:7d19 on br-abcfb14d7511.
Withdrawing address record for 192.168.16.1 on br-abcfb14d7511.
Withdrawing address record for fe80::42:9aff:fefb:9d36 on br-757af210df57.
Withdrawing address record for 172.30.0.1 on br-757af210df57.
Withdrawing address record for fe80::c234:fcc:96d3:4cec on eno1.
Withdrawing address record for 192.168.1.8 on eno1.
Withdrawing address record for ::1 on lo.
Withdrawing address record for 127.0.0.1 on lo.
Host name conflict, retrying with lucy-timemachine-2
Registering new address record for fe80::6846:e9ff:fe07:2b79 on veth3bee38d.*.
Registering new address record for fe80::2448:60ff:fee5:cb32 on veth21bf53a.*.
Registering new address record for fe80::d06c:e7ff:fe9c:55f5 on vethe2ca1fa.*.
Registering new address record for fe80::a033:2aff:fe46:8a06 on veth98d62c8.*.
Registering new address record for fe80::68df:37ff:fe58:975e on vethc64d769.*.
Registering new address record for fe80::ec05:eff:fe9d:75bb on veth7d9447f.*.
Registering new address record for fe80::acd2:adff:fe7f:a806 on vethda9432f.*.
Registering new address record for fe80::f81a:35ff:fe2d:da4d on veth74b074f.*.
Registering new address record for fe80::b4db:92ff:fe40:730b on vethc06d52f.*.
Registering new address record for fe80::3cac:64ff:fea1:1ad5 on vethc9c79d1.*.
Registering new address record for fe80::9406:10ff:feb8:b1cf on veth7a70b29.*.
Registering new address record for fe80::cf6:f6ff:fe09:206e on veth920a57e.*.
Registering new address record for fe80::1442:76ff:fe6d:1e60 on veth9cfac2a.*.
Registering new address record for fe80::f8fb:75ff:feff:4fae on veth9739fa3.*.
Registering new address record for fe80::982b:fbff:fe41:196c on veth05b0a51.*.
Registering new address record for fe80::b8a8:e6ff:feb2:efba on veth77e4f7e.*.
Registering new address record for fe80::78b3:91ff:fe49:739e on veth76bfad9.*.
Registering new address record for fe80::24d5:49ff:fe32:2a4f on veth24ea4d6.*.
Registering new address record for fe80::186e:80ff:fe27:ba5c on vetha3eaf9f.*.
Registering new address record for fe80::28f3:9fff:fec9:fd19 on veth9f19510.*.
Registering new address record for fe80::cc08:50ff:fe4a:c704 on vethfc4c418.*.
Registering new address record for fe80::4a1:c3ff:fefd:9e71 on vethffd7332.*.
Registering new address record for fe80::1838:37ff:feaa:faa0 on veth4692833.*.
Registering new address record for fe80::181f:3eff:fe95:6fb8 on veth32428e1.*.
Registering new address record for fe80::5c66:9bff:fe47:cc46 on veth9f8e81a.*.
Registering new address record for fe80::6828:42ff:fee8:462 on veth5d88477.*.
Registering new address record for fe80::c63:40ff:fe55:b03e on veth501f12c.*.
Registering new address record for fe80::8c68:a6ff:fe74:480c on veth6e094eb.*.
Registering new address record for fe80::cc6a:9ff:fef7:c3bb on veth0d7dbfd.*.
Registering new address record for fe80::42:eeff:fe45:848b on br-c557176ba5db.*.
Registering new address record for 172.20.0.1 on br-c557176ba5db.IPv4.
Registering new address record for fe80::42:dcff:fe33:1eb7 on br-75f239d52eba.*.
Registering new address record for 172.27.0.1 on br-75f239d52eba.IPv4.
Registering new address record for fe80::42:ecff:feb2:2f57 on br-30d9e6417e2c.*.
Registering new address record for 172.21.0.1 on br-30d9e6417e2c.IPv4.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::42:2eff:fe9c:1eee on br-4ef159e28a8a.*.
Registering new address record for 172.23.0.1 on br-4ef159e28a8a.IPv4.
Registering new address record for fe80::42:78ff:fe84:400f on br-366a3f5dd6ee.*.
Registering new address record for 172.18.0.1 on br-366a3f5dd6ee.IPv4.
Registering new address record for fe80::42:39ff:fe16:6018 on br-ce53aa0024a6.*.
Registering new address record for 192.168.99.1 on br-ce53aa0024a6.IPv4.
Registering new address record for fe80::42:3fff:fef2:bf99 on br-bc5eed1519f2.*.
Registering new address record for 172.19.0.1 on br-bc5eed1519f2.IPv4.
Registering new address record for fe80::42:59ff:fe02:7d19 on br-abcfb14d7511.*.
Registering new address record for 192.168.16.1 on br-abcfb14d7511.IPv4.
Registering new address record for fe80::42:9aff:fefb:9d36 on br-757af210df57.*.
Registering new address record for 172.30.0.1 on br-757af210df57.IPv4.
Registering new address record for fe80::c234:fcc:96d3:4cec on eno1.*.
Registering new address record for 192.168.1.8 on eno1.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Withdrawing address record for fe80::2448:60ff:fee5:cb32 on veth21bf53a.
Withdrawing address record for fe80::d06c:e7ff:fe9c:55f5 on vethe2ca1fa.
Withdrawing address record for fe80::a033:2aff:fe46:8a06 on veth98d62c8.
Withdrawing address record for fe80::68df:37ff:fe58:975e on vethc64d769.
Withdrawing address record for fe80::ec05:eff:fe9d:75bb on veth7d9447f.
Withdrawing address record for fe80::acd2:adff:fe7f:a806 on vethda9432f.
Withdrawing address record for fe80::f81a:35ff:fe2d:da4d on veth74b074f.
Withdrawing address record for fe80::b4db:92ff:fe40:730b on vethc06d52f.
Withdrawing address record for fe80::3cac:64ff:fea1:1ad5 on vethc9c79d1.
Withdrawing address record for fe80::9406:10ff:feb8:b1cf on veth7a70b29.
Withdrawing address record for fe80::cf6:f6ff:fe09:206e on veth920a57e.
Withdrawing address record for fe80::1442:76ff:fe6d:1e60 on veth9cfac2a.
Withdrawing address record for fe80::f8fb:75ff:feff:4fae on veth9739fa3.
Withdrawing address record for fe80::982b:fbff:fe41:196c on veth05b0a51.
Withdrawing address record for fe80::b8a8:e6ff:feb2:efba on veth77e4f7e.
Withdrawing address record for fe80::78b3:91ff:fe49:739e on veth76bfad9.
Withdrawing address record for fe80::24d5:49ff:fe32:2a4f on veth24ea4d6.
Withdrawing address record for fe80::186e:80ff:fe27:ba5c on vetha3eaf9f.
Withdrawing address record for fe80::28f3:9fff:fec9:fd19 on veth9f19510.
Withdrawing address record for fe80::cc08:50ff:fe4a:c704 on vethfc4c418.
Withdrawing address record for fe80::4a1:c3ff:fefd:9e71 on vethffd7332.
Withdrawing address record for fe80::1838:37ff:feaa:faa0 on veth4692833.
Withdrawing address record for fe80::181f:3eff:fe95:6fb8 on veth32428e1.
Withdrawing address record for fe80::5c66:9bff:fe47:cc46 on veth9f8e81a.
Withdrawing address record for fe80::6828:42ff:fee8:462 on veth5d88477.
Withdrawing address record for fe80::c63:40ff:fe55:b03e on veth501f12c.
Withdrawing address record for fe80::8c68:a6ff:fe74:480c on veth6e094eb.
Withdrawing address record for fe80::cc6a:9ff:fef7:c3bb on veth0d7dbfd.
Withdrawing address record for fe80::42:eeff:fe45:848b on br-c557176ba5db.
Withdrawing address record for 172.20.0.1 on br-c557176ba5db.
Withdrawing address record for fe80::42:dcff:fe33:1eb7 on br-75f239d52eba.
Withdrawing address record for 172.27.0.1 on br-75f239d52eba.
Withdrawing address record for fe80::42:ecff:feb2:2f57 on br-30d9e6417e2c.
Withdrawing address record for 172.21.0.1 on br-30d9e6417e2c.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for fe80::42:2eff:fe9c:1eee on br-4ef159e28a8a.
Withdrawing address record for 172.23.0.1 on br-4ef159e28a8a.
Withdrawing address record for fe80::42:78ff:fe84:400f on br-366a3f5dd6ee.
Withdrawing address record for 172.18.0.1 on br-366a3f5dd6ee.
Withdrawing address record for fe80::42:39ff:fe16:6018 on br-ce53aa0024a6.
Withdrawing address record for 192.168.99.1 on br-ce53aa0024a6.
Withdrawing address record for fe80::42:3fff:fef2:bf99 on br-bc5eed1519f2.
Withdrawing address record for 172.19.0.1 on br-bc5eed1519f2.
Withdrawing address record for fe80::42:59ff:fe02:7d19 on br-abcfb14d7511.
Withdrawing address record for 192.168.16.1 on br-abcfb14d7511.
Withdrawing address record for fe80::42:9aff:fefb:9d36 on br-757af210df57.
Withdrawing address record for 172.30.0.1 on br-757af210df57.
Withdrawing address record for fe80::c234:fcc:96d3:4cec on eno1.
Withdrawing address record for 192.168.1.8 on eno1.
Withdrawing address record for ::1 on lo.
Withdrawing address record for 127.0.0.1 on lo.
Host name conflict, retrying with lucy-timemachine-3

**Comment by mbentley** [comment]
You're almost certainly seeing a mDNS (multicast DNS) conflict with the host.  Do you have Avahi enabled or running on the host?  If so, take a look at this: https://github.com/mbentley/docker-timemachine#conflicts-with-samba-andor-avahi-on-the-host

I also see some references related to systemd-resolved and it possibly enabling mDNS as well which conflicts with the container since it is running in host mode.  Maybe check `/etc/systemd/resolved.conf` as described [here](https://unix.stackexchange.com/a/574006).

**Comment by vhaasteren** [comment]
Thanks! That seems to be it. Not sure what enabled it on the host, or when, but it sounds like the best way forward is by going the macvlan route.  I tried doing the avahi reflection, but that didn't resolve it, and macvlan seems neater. I don't have it fully working yet though, so...

Question about that: adding your "Example macvlan setup using docker-compose" almost to the letter, the backup disk shows up when trying "Select backup Disk", but when selecting it the server blocks it with the message "This file server will not allow any additional users to log on. Try to connect again later."

Is there something else I need to change when changing to macvlan? This exact setup had been working before

**Comment by vhaasteren** [comment]
Oh... it started working when I changed the userid to 1001 (and changing the volume ownership accordingly). I don't understand, I simply tried it because it said in the log message "getpwuid(1001)". Any idea why that would be required?

But, I can add a linux user called 'timemachine', so that the username on the host system makes sense, so I think I'm happy enough already
