### ISSUE TITLE
[Feature]: LDAP auth

### ISSUE THREAD

**Issue by mr-falken** [mbentley/docker-timemachine#121]
### What problem are you looking to solve?

Hi and thanks for the great job!
Just like the tiles says, any chance to get ldap auth integration in the roadmap ?

**Comment by mbentley** [comment]
I can honestly say that I haven't tried to do LDAP previously with Samba; let alone in a container so I am not sure what caveats there might be.  I'd have to do some digging in to figure out how to do that exactly.

**Comment by baurmatt** [comment]
I would also be interested in this feature! :)

**Comment by mbentley** [comment]
Unfortunately, this does not appear to be possible based on a few resources I found:
https://serverfault.com/a/1043795
https://ubuntu.com/server/docs/samba-openldap-backend

Happy to be wrong so if anyone finds something to the contrary that doesn't include joining a container via kerberos (I will most definitely not be implementing that), then it won't be possible.
