### ISSUE TITLE
[Bug]: Bad Switch

### ISSUE THREAD

**Issue by jurjevic** [mbentley/docker-timemachine#125]
### Describe the Bug

I followed the instruction and also did `chown -R 1000:1000`on my tm directory. In the directory, there was alread a sparsebundle backup, which I would like to reuse.

When starting backup, the docker log gets poluted with hundres of error "Bad Switch" 

`parse_dos_attribute_blob: bad ndr decode from EA on file XXXXX.sparsebundle/mapped: Error = Bad Switch
ndr_pull_xattr_DosInfo: ndr_pull_error(Bad Switch): Bad switch value 5 at librpc/gen_ndr/ndr_xattr.c:390 at librpc/gen_ndr/ndr_xattr.c:390`

### Expected Behavior

No errors in log file

### Steps to Reproduce

1. Start container
2. Start backup

### How You're Launching the Container

```plain
docker run
  -d
  --name='TimeMachine'
  --net='eth0'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="TimeMachine"
  -e 'VOLUME_SIZE_LIMIT'='5 T'
  -e 'TM_USERNAME'='timemachine'
  -e 'PASSWORD'='xxx'
  -e 'ADVERTISED_HOSTNAME'='TimeMachine'
  -e 'CUSTOM_SMB_CONF'='false'
  -e 'CUSTOM_USER'='false'
  -e 'DEBUG_LEVEL'='1'
  -e 'MIMIC_MODEL'='TimeCapsule8,119'
  -e 'EXTERNAL_CONF'=''
  -e 'HIDE_SHARES'='no'
  -e 'TM_GROUPNAME'='timemachine'
  -e 'TM_UID'='1000'
  -e 'SET_PERMISSIONS'='false'
  -e 'SMB_INHERIT_PERMISSIONS'='no'
  -e 'SMB_NFS_ACES'='yes'
  -e 'SMB_METADATA'='stream'
  -e 'SMB_PORT'='445'
  -e 'SMB_VFS_OBJECTS'='acl_xattr fruit streams_xattr'
  -e 'WORKGROUP'='WORKGROUP'
  -e 'TM_GID'='1000'
  -e 'SHARE_NAME'='timemachine'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://upload.wikimedia.org/wikipedia/de/f/f4/Time_Machine_%28Apple%29_Logo.png'
  -v '/mnt/user/timecapsule':'/opt/timemachine':'rw'
  --hostname timemachine 'mbentley/timemachine' 
8c572aab707f43abbb1a14474a8be461b9b978dbe38b09e8f41fb695c21920f9
```

### Container Logs

```plain
ndr_pull_xattr_DosInfo: ndr_pull_error(Bad Switch): Bad switch value 5 at librpc/gen_ndr/ndr_xattr.c:390 at librpc/gen_ndr/ndr_xattr.c:390
parse_dos_attribute_blob: bad ndr decode from EA on file xxx.sparsebundle/bands/532: Error = Bad Switch
```

**Comment by mbentley** [comment]
What is the filesystem type where `/mnt/user/timecapsule` is mounted?

**Comment by jurjevic** [comment]
The filesystem is XFS.

Thats possible thats is comes from the prvious sparsebundle. I just don't want to lose all the data.
What is the meaning of the error?

**Comment by mbentley** [comment]
I don't know what the error means.  Google doesn't return much and I can't tell from the [source code](https://github.com/samba-team/samba/blob/5c051eacd425f322995ab53fce74028e44109046/pidl/lib/Parse/Pidl/Samba4/NDR/Parser.pm#L2127) right offhand what exactly it's doing.

**Comment by jurjevic** [comment]
Okay. Thank you anyway. At least I can confirm, that clean backup doesn't  produce this error.

Maybe you could put it into the README as a known issue.

**Comment by jurjevic** [comment]
Removed old backup and started from clean setup.
