### ISSUE TITLE
Custom User(s)

### ISSUE THREAD

**Issue by trickert76** [mbentley/docker-timemachine#16]
In case of using a custom afpd.conf it is -in my case- also useful to use custom users and not only the one user timemachine.  So I mount /etc/passwd, shadow and group into the container and expected that the service uses the user in it (which works for the custom afpd.conf) but the entrypoint script always tries to install the timemachine user.

Is it possible to add a new flag (maybe custom_users or so) and if it is set ignore the adduser+setpass commands in the entrypoint.sh shell?

**Comment by mbentley** [comment]
What about creating the directory `/opt/${TM_USERNAME}`?  Should I assume you're handling that as well if you're providing your own users?

**Comment by mbentley** [comment]
Take a look at https://github.com/mbentley/docker-timemachine/pull/17; I think that should do it.

**Comment by mbentley** [comment]
@trickert76 - just curious if you had a chance to take a look.
