### ISSUE TITLE
Should the healthcheck.sh fail fast or slow?

### ISSUE THREAD

**Issue by aussiDavid** [mbentley/docker-timemachine#30]
Looking at this file [/healthcheck.sh](https://github.com/mbentley/docker-timemachine/blob/master/healthcheck.sh), I was wondering if the health check should fail if **any** `dbus-daemon afpd avahi-daemon` processes fail, or only if **all** 3 have failed. It is not clear without knowing the purpose of each process.

```bash
# Initialize variables
EXITCODE="0"
PROCESSES="dbus-daemon afpd avahi-daemon"

# check to see if processes are running
for i in ${PROCESSES}
do
  if pgrep "${i}" >/dev/null 2>&1
  then
    # process is running
    echo "${i} is running"
  else
    # process is not running
    echo "${i} is NOT running"
    EXITCODE="1"
  fi
done

# exit returning proper exit code
exit ${EXITCODE}
```

**Comment by mbentley** [comment]
It should fail if any of them are not functioning which is what it will do.  Once it loops through each, it will return the exit code.  If any of them are not running, they will flip the exit code to 1.

**Comment by aussiDavid** [comment]
> they will flip the exit code

Ah. I missed that bit. Thank you.
