### ISSUE TITLE
SMB Image does not fully advertise as TimeMachine targe

### ISSUE THREAD

**Issue by derreisende77** [mbentley/docker-timemachine#35]
I successfully run the **SMB** image with following cmd:

```bash
sudo docker run -d --restart=always \
  --name timemachine \
  --network=timemachine \
  --hostname "TimeCapsule" \
  -e CUSTOM_SMB_CONF="false" \
  -e CUSTOM_USER="false" \
  -e DEBUG_LEVEL="1" \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e EXTERNAL_CONF="" \
  -e HIDE_SHARES="no" \
  -e TM_USERNAME="timemachine" \
  -e TM_GROUPNAME="timemachine" \
  -e TM_UID="1000" \
  -e TM_GID="1000" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="false" \
  -e SHARE_NAME="TimeMachine" \
  -e VOLUME_SIZE_LIMIT="4 T" \
  -e WORKGROUP="WORKGROUP" \
  -v timemachine-backup-data:/opt/timemachine \
  -v timemachine-var-log:/var/log \
  -v timemachine-var-lib-samba:/var/lib/samba \
  -v timemachine-var-cache-samba:/var/cache/samba \
  -v timemachine-run-samba:/run/samba \
  mbentley/timemachine:smb
```

However I noticed that the container does not fully advertise as a TimeMachine target via avahi. I modified my setup such way that `/etc/avahi/services/smbd.service` contains the following entries to make it visible in the TimeMachine settings dialog without further login etc:

```xml
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_smb._tcp</type>
    <port>445</port>
  </service>
  <service>
    <type>_device-info._tcp</type>
    <port>9</port>
  <txt-record>model=TimeCapsule8,119</txt-record>
  </service>
<service>
    <type>_adisk._tcp</type>
    <port>9</port>
    <txt-record>dk0=adVN=TimeMachine,adVF=0x82</txt-record>
    <txt-record>sys=adVF=0x100</txt-record>
  </service>
</service-group>
```

I use `<port>9</port>` in all descriptions as this used to be the original value by Apple instead of `<port>0</port>`. And I found on searching the net that there might be problems by using port 0.

Furthermore I added the `_adisk._tcp` description according to [this link](https://developer.apple.com/library/archive/releasenotes/NetworkingInternetWeb/Time_Machine_SMB_Spec/index.html#//apple_ref/doc/uid/TP40017496-CH1-SW1).

`model=TimeCapsule8,119` should contain the `MIMIC_MODEL` variable and `dk0=adVN=TimeMachine,adVF=0x82` should contain `SHARE_NAME` for `adVN`.

It would be great if you could modify your image to include the above setup in a next version.

**Comment by mbentley** [comment]
Thanks for the findings!  This is the same as #34.  I'm going to close this in favor of #34 but bring the text over.
