### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by derreisende77** [mbentley/docker-timemachine#37]
I am now successfully running the container on a Synology NAS system which already has native Samba and avahi services running.

Being a newbie with docker and using the examples in README.md I struggled quite a bit because of issues with the timemachine avahi overriding the NAS advertisements when using host networking or bridge mode (warnings are in the container log).

I would suggest to include a small section for users who want to use the image on a NAS by hinting them to maybe setup a macvlan network instead of host/bridge networking. This way they can keep their NAS setup and do get (in case of Synology) a way more stable TimeMachine.

**Comment by mbentley** [comment]
I just pushed a new commit to update the [README](https://github.com/mbentley/docker-timemachine/pull/36/commits/23c0d2a2015c216c69ff17609f818190488b62ee#diff-04c6e90faac2675aa89e2176d2eec7d8) to #36 to address the above.  Thanks for the suggestion!  I personally run with `macvlan` myself for this very reason.

**Comment by derreisende77** [comment]
Looking great! Maybe one suggestion for Synology DSM users: Here "eth0" may also be called "ovs_eth0" due to Open vSwitch software (e.g. if virtualization is enabled).

**Comment by mbentley** [comment]
Does this command output the correct network interface on your Synology?

```
route | grep ^default | awk '{print $NF}'
```

**Comment by derreisende77** [comment]
yes it outputs ovs_eth0 which is my default network interface

**Comment by mbentley** [comment]
Thanks for checking.  https://github.com/mbentley/docker-timemachine/pull/36/commits/053c2eb6f14664ffe73f3bea5ce84acbac140583#diff-04c6e90faac2675aa89e2176d2eec7d8 includes an example command to find the primary network interface but also mentions that an alternate interface can be used; I'll leave further configuration to the reader as this should work for most people.

**Comment by derreisende77** [comment]
Yes this should be more than enough help for others to get started.

**Comment by mbentley** [comment]
Thanks for taking a look and I appreciate all of the feedback!
