### ISSUE TITLE
Configure Drive Manually

### ISSUE THREAD

**Issue by juan11perez** [mbentley/docker-timemachine#4]
First of all thank you for this container. 
I had to set up manual port as the container was clashing with samba and effectively crashing.

you're notes mention "configure the drive manually". But Im a bit lost there. 
Appreciate if you could offer some guidance on how to do this.

Thank you

**Comment by mbentley** [comment]
Basically you need to connect to the share through finder
`afp://hostname/TimeMachine`

For example:
<img width="598" alt="screenshot 2018-08-30 at 5 11 55 pm" src="https://user-images.githubusercontent.com/414445/44879496-d0dc8a00-ac77-11e8-91b2-8b120f8ab5e9.png">

**Comment by juan11perez** [comment]
Thank you for your time. I couldn't get it to work.
it conflicts with the samba instance regardless of using net=host or exposing ports.

**Comment by mbentley** [comment]
Dis you try changing the exposed ports to prevent the conflict?

**Comment by juan11perez** [comment]
Matt, thank you. I did but it didnt work. the "normal" shares kept dissapearing and the timemachine share didnt want to accept the ussername:password.
