### ISSUE TITLE
Speed of Transfer

### ISSUE THREAD

**Issue by justinglock40** [mbentley/docker-timemachine#41]
Any recommendations for speed transfer. Mine is capped at 4-5MB/s on 5GHz channel and Time Machine hardwired. Regular upload to server I can pull up to 40MB/s with like a movie

**Comment by justinglock40** [comment]
Disable throttle
`sudo sysctl debug.lowpri\_throttle_enabled=0`
reboot

Enable throttle after initial backup
`sudo sysctl debug.lowpri\_throttle_enabled=1`
reboot

**Comment by sifex** [comment]
Difference is night and day, cheers <3

**Comment by pascalwhoop** [comment]
I just ran into the same and found this. Never happened to me before, but this is a company laptop. Is this a non-default setting that IT may have set for some odd reason?

**Comment by mbentley** [comment]
The default setting is to be throttled as to not impact regular usage.
