### ISSUE TITLE
Perhaps you could build ARMv7 images?

### ISSUE THREAD

**Issue by perbu** [mbentley/docker-timemachine#42]
Hi.

This was very useful - thanks! I just built and deployed this on my raspberry pi 4. Everything seems to be working fine. The pi has plenty CPU and memory to run this and is a pretty perfect platform to run time machine.

I'm not sure how you build but I suppose you could easily find a build service that would build this for the ARMv7 architecture.

Let me know if I can help out.

**Comment by boda2004** [comment]
as a quick workaround - just clone this repo and run following command `docker build -t timemachine -f Dockerfile.smb docker-timemachine` on ARMv7 host (assuming alpine has all required packages available for target platform). If everything's fine - you'll be able to run it as stated in readme (just replace `mbentley/timemachine:smb` with `timemachine`)

**Comment by mbentley** [comment]
I might be able to do a cross compile using buildx. I don’t think there is anything unusual in the image that wouldn’t be available for armv7l right offhand.

**Comment by perbu** [comment]
As I said, I've successfully built and ran this in Docker on a rPi4 without any changes. So everything works. You just need a buildhost that can build on arm in addition to x86.

**Comment by mbentley** [comment]
I setup a job to build using `buildx` which is now pushing to `mbentley/timemachine:smb-armv7l`.  Could you take a look and see if that works?

**Comment by perbu** [comment]
hi.

The container deployed nicely on rPi. Thanks!

I've forked your repo and made a github action which pushes to docker hub for a number of architectures. If you want a PR just say so. You can poke around https://github.com/perbu/docker-timemachine/actions if you wanna look.

Never used Github actions before. It seems nice and together with buildx multiarch docker seems trivial.

**Comment by mbentley** [comment]
Thanks for checking to make sure it worked, much appreciated.  I haven't had a chance to mess with GitHub actions myself; I'm just using Jenkins + a webhook to build to an engine w/buildx.

**Comment by perbu** [comment]
ok.

I'll close the issue. If you want to scrap your jenkins the github actions file is here for your inspiration: https://github.com/perbu/docker-timemachine/blob/master/.github/workflows/docker-buildx.yml
