### ISSUE TITLE
Readme: Filesystem recommendation

### ISSUE THREAD

**Issue by JEK58** [mbentley/docker-timemachine#44]
The readme doesn't say anything about the recommended filesystem for to "Path to backup to" 
Does it matter at all? Since most user may use an external drive for the TM path.

**Comment by mbentley** [comment]
If you can find some file system requirements or recommendations, I’ll add them but I can find nothing regarding any requirements for a backing file system behind a Samba share.  Apple only mentions file systems recommended when using a local, direct attached backup: https://support.apple.com/guide/mac-help/types-of-disks-you-can-use-with-time-machine-mh15139/mac

**Comment by smfoo** [comment]
OK, I'll get back to you. Just tested ext4 and it's working. Will possibly try out some others.

**Comment by smfoo** [comment]
Can you give some advice on using HFS+? I'm running into permissions issues, where the Mac cannot write to the TM. How did you do it? I mounted an external drive with -o uid=1000,gid=1000. No matter if I formatted the drive on my docker host, or my Mac I always get the error "You do not have the necessary read, write and append privileges on the selected network backup disk." when attempting to backup.

**Comment by mbentley** [comment]
I've used xfs, ext4, and zfs for TimeMachine successfully in the past.  The docker image can automatically set permissions `-e SET_PERMISSIONS="true"` so if it is still throwing errors, it could be a HFS+ and Samba issue.  Using 1000:1000 should be fine with the image defaults anyway if you don't let it set permissions on your behalf so there must be something else preventing it from working with HFS+.

**Comment by smfoo** [comment]
Thanks I will look into that.

Regarding filesystems: According to [this](https://en.wikipedia.org/wiki/Sparse_image#Sparse_bundle_disk_images) wikipedia article it doesn't matter at all with sparsebundles: 

> the backup destination no longer needs to be a Hierarchical File System (HFS) volume (for the hard links to work and to preserve metadata), but can be any shared folder, on any server, connected using any protocol and using any file system to store the actual files



Unfortunately the references in the article are outdated

**Comment by theg1nger** [comment]
@JEK58 
I ran into the same issue with HFS+. I couldn't get the HFS+ drive to mount as rw until I installed 'hfsprogs' on the host system. 

My fstab entry looks like this
`/dev/disk/by-uuid/UUIDOFTHEUSBDRIVE /media/MYMOUNTDIR hfsplus force,rw,nofail,uid=1000 0 0`

hope this helps.

**Comment by saildot4k** [comment]
Any documentation to get this running within Win 10 docker?

**Comment by mbentley** [comment]
I don't think that a bind mount to the Windows 10 filesystem would work.  You may just need to use a Docker named volume but that would store the data inside of the Docker for Windows VM which isn't ideal.  Honestly, I would not run time Machine on Docker for Windows.

**Comment by mbentley** [comment]
Closing; please reopen if there is still a persistent issue.  Samba should more or less hide the file system that is exposed to the Mac.
