### ISSUE TITLE
Unable to accept connections after the last change?

### ISSUE THREAD

**Issue by aovestdipaperino** [mbentley/docker-timemachine#47]
I have a script to recreate and run the container and recently the container started to refusing connections (from all clients: Windows, MacOS, Linux).
I don't think the latest changes have anything to do but just wondering in case. I will start troubleshooting

My script

```
docker rm -f timemachine
docker run -d \
  --restart always \
  --name timemachine \
  -h timemachine \
  --net macnet32 \
  --ip 192.168.2.200 \
  -e CUSTOM_SMB_CONF="false" \
  -e CUSTOM_USER="false" \
  -e DEBUG_LEVEL="1" \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e HIDE_SHARES="no" \
  -e TM_USERNAME="timemachine" \
  -e TM_GROUPNAME="timemachine" \
  -e TM_UID="1000" \
  -e TM_GID="1000" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="false" \
  -e SHARE_NAME="TimeMachine" \
  -e SMB_PORT="445" \
  -e VOLUME_SIZE_LIMIT="0" \
  -e WORKGROUP="WORKGROUP" \
  -v /Backup/timemachine/TimeMachine:/opt/timemachine \
  -v /Backup/timemachine/TM_Config/var-lib-samba:/var/lib/samba \
  -v /Backup/timemachine/TM_Config/var-cache-samba:/var/cache/samba \
  -v /Backup/timemachine/TM_Config/run-samba:/run/samba \
  mbentley/timemachine:smb
```
Sample error:
![image](https://user-images.githubusercontent.com/42046613/87071986-e4d86780-c1cf-11ea-941b-bc324ba67f05.png)

**Comment by mbentley** [comment]
The container logs would be great. Also, I would suggest stopping the container and then removing it. I am not sure if there is any problem if connections are killed which is what rm -f will do.

**Comment by aovestdipaperino** [comment]
It was a permission screwup probably by an abrupt stop.
Since the purpose of the script is creation of the container from scratch, this line fixed it:

`/Backup/timemachine/TM_Config/*`

Thanks for the tip, closing it!
PS: debug_level = 10 is deadly
![image](https://user-images.githubusercontent.com/42046613/87075947-f02e9180-c1d5-11ea-8562-1130c7882c36.png)

**Comment by mbentley** [comment]
lol Good deal
