### ISSUE TITLE
OSStatus error 2

### ISSUE THREAD

**Issue by mcfire02** [mbentley/docker-timemachine#5]
Hi,
i'm trying to set up a Time Machine backup using your docker image. I have been successful to create the container, i can see my server under the Available Disk option in the TimeMachine utility. But when i select it and enter the default user and password and have the Following error message. 
Any help would be appreciated. Thank you
<img width="668" alt="screen shot 2019-01-19 at 12 44 30 am" src="https://user-images.githubusercontent.com/46835505/51422853-3fb57380-1b84-11e9-8807-0f64b0477f02.png">

**Comment by mbentley** [comment]
Sorry for not getting back to your sooner.  I am wondering if it is related to permissions on the volume.  What is your `docker run` command (minus any passwords)?  By default, the `timemachine` account inside the container is being created as `timemachine:timemachine` with a UID/GID of `1000:1000`.  You might have to `chown` the host mount path to `1000:1000` for it to work as I suspect that might be it.

**Comment by mcfire02** [comment]
Hi, Thanks for your response. So i removed the container and i created it again without any "-v" command and it works perfectly.

**Comment by mbentley** [comment]
OK, good to know.  In that case, it is most likely the ownership on wherever the volume is.  Changing them should make it work properly.  Without the `-v` to mount `/opt/timemachine` from inside the container to outside, it will cause an issue.  I think I can actually just make the entrypoint script smarter to automatically set the permissions, or at least make it an option.

**Comment by mcfire02** [comment]
Sorry for the question if it's obvious but, how do i change the ownership/permission on the volume ? Like what is the command ? Thanks

**Comment by mbentley** [comment]
No problem.

So in this example, I want `/data/timemachine` to be the location on my host where the volume is mapped to. In that case, your docker command would look like this:

```
docker run -d --restart=always \
  --net=host \
  --name timemachine \
  -e PASSWORD="timemachine" \
  -e VOLUME_SIZE_LIMIT="0" \
  -e LOG_LEVEL="info" \
  -e MIMIC_MODEL="TimeCapsule6,106" \
  -e SHARE_NAME="TimeMachine" \
  -v /data/timemachine:/opt/timemachine \
  -v timemachine-logs:/var/log/supervisor \
  mbentley/timemachine:latest
```

Before you run the container, you should be able to change the ownership and permissions using:
```
chown 1000:1000 /data/timemachine
chmod 755 /data/timemachine
```

Add `sudo` in front of both of the commands if you're not root.

**Comment by mcfire02** [comment]
Ok cool ! Thank you very much for your help and thanks again for your docker image.
