### ISSUE TITLE
[Big Sur Beta 7] There was an error configuring “/Volumes/***” as a Time Machine backup disk.

### ISSUE THREAD

**Issue by JPyke3** [mbentley/docker-timemachine#55]
Hi there!

Thanks for this really cool project! I have it working really well on one of my machines :)

However, on my other machine (Which is actually running the Big Sur beta) I am unable to get this to work. I get the following error message after going to time machine, choosing the correct share for my user, and entering the details correctly:
```
There was an error configuring “/Volumes/***” as a Time Machine backup disk.
```
_*** is a substitution for the actual shares name_

On my Catalina machine, it works really well. It connected no worries, and it's currently creating its first backup now :)

I wouldn't really know where to start debugging this, so this is where I am asking for a bit of help, here are some logs from the container itself, they perhaps point towards a problem?:
```
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 58 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 58): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 67 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 67): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 87 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 87): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
timemachine     | Failed to fetch record!
timemachine     | pcap cache not loaded
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 94 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 94): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
timemachine     | smb2_validate_sequence_number: smb2_validate_sequence_number: bad message_id 3 (sequence id 3) (granted = 1, low = 2, range = 1)
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 110 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 110): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
timemachine     | ===============================================================
timemachine     | INTERNAL ERROR: Signal 11 in pid 118 (4.12.2)
timemachine     | If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
timemachine     | ===============================================================
timemachine     | PANIC (pid 118): internal error
timemachine     | unable to produce a stack trace on this platform
timemachine     | dumping core in /var/log/samba/cores/smbd
```

And in case it is needed: My `docker-compose.yaml` file:
```
version: "2.1"
services:
  time-machine:
    image: mbentley/timemachine:smb-armv7l
    container_name: timemachine
    network_mode: host
    environment:
      - SHARE_NAME=TimeMachine
      - EXTERNAL_CONF=/conf
    volumes:
      - /home/jacob/Time-Machine/users:/conf
      - /home/jacob/Time-Machine/timemachine/var-lib-samba:/var/lib/samba
      - /home/jacob/Time-Machine/timemachine/var-cache-samba:/var/cache/samba
      - /home/jacob/Time-Machine/timemachine/run-samba:/run/samba
      - /mnt/cache/Time-Machine/*:/opt/*
      - /mnt/cache/Time-Machine/*:/opt/*
```

The `.conf` file for the specific user:
```
TM_USERNAME=*
TM_GROUPNAME=*group
PASSWORD=***
SHARE_NAME=*s-timemachine
VOLUME_SIZE_LIMIT="300 G"
TM_UID=1000
TM_GID=1000
```
_A few substitutions for the names, I have checked and made sure everything is right_

I am not too familiar with Samba and with how Time Machine specifically works, so perhaps someone would be able to point me in the right direction? Happy to do any debugging steps or provide any logs :)

I appreciate the help! And cheers for the great project!

_EDIT: Nice, after all my redactions still forgot something :P_

**Comment by mbentley** [comment]
Thanks for the report.  I can reproduce this as well as my time machine backups stopped happening 2 days ago; checked the logs and there it is.  I'll have to see if I can find something, either with the version of Alpine, Samba, or something of that nature.  I haven't seen this error before so it's definitely something new.

**Comment by JPyke3** [comment]
No worries. Keep us updated, I might take a bit of a dig this afternoon as well. Keen to try anything new when it comes up 👍

**Comment by mbentley** [comment]
Does the error ever stop repeating for you?  It's odd as well seeing as I am on x86 and you're on arm which would lead me to believe it might be something in the latest packaging.  Per the Alpine package index, the latest Samba was built on 10/6 so it was recent.  Based on the cadence of when I trigger rebuilds (on Saturdays), that would mean that it would have built the new image this last Saturday.  But that being said, I also manually build the arm image on Jenkins and it hasn't actually re-triggered a build in a while as there have been no updates to the base image.

I am curious - what filesystem is your storage that you have bind mounted into the container?

**Comment by JPyke3** [comment]
Nah, to me at least it seems like the error is only triggered when attempting to setup the Time Machine on my MacBook, if I just leave it alone the VM will just keep going without logs.

Filesystem of the mounted storage is `ext4`. The actual docker filesystem is `overlay2`.

**Comment by mbentley** [comment]
OK great.  Thanks for that.  It helps me narrow things down a bit.  I might have to get Big Sur installed on an external disk to check it out to see if there is something different there.  Of course my Mac isn't cooperating and won't even connect to my time machine at all right now so I'll have to get that figured out first.

**Comment by JPyke3** [comment]
Hey I got it to work! check this out: https://developer.apple.com/forums/thread/659331.

Seems like this issue is specific to Beta 7, doesn't connect to SMB properly. Literally ran this command:
`sudo kextload /System/Library/Extensions/smbfs.kext` and ran like a treat after that.

This is my dev machine so I am really not all that phased by running random commands on my machine. Hopefully this isn't rolled into GM?

**Comment by JPyke3** [comment]
It does show my SMB server as having 0KB so that's an issue, but at least we're connecting now 😂

**Comment by mbentley** [comment]
Oh, it's showing that the disk has 0KB available or that it has 0KB previously backed up?  You're good on the size limit syntax so that's strange.

**Comment by JPyke3** [comment]
<img width="422" alt="Screen Shot 2020-10-15 at 1 37 47 pm" src="https://user-images.githubusercontent.com/13283054/96118319-9e3f8b00-0eeb-11eb-8381-1bb7b0a62010.png">

That's what I got there, it will try for ages to Look for backup disk, and then it will just go back to the time machine screen where it shows I never made a backup:

<img width="300" alt="Screen Shot 2020-10-15 at 1 39 02 pm" src="https://user-images.githubusercontent.com/13283054/96118444-cc24cf80-0eeb-11eb-9ffe-61f970f0337b.png">

Perhaps it's just an issue with this specific version of Big Sur and SMB? I'll keep perusing the apple dev forums

**Comment by JPyke3** [comment]
... btw it's an issue with this machine specifically as the Catalina machine does report the correct size for the storage

**Comment by JPyke3** [comment]
<img width="713" alt="Screen Shot 2020-10-15 at 1 41 16 pm" src="https://user-images.githubusercontent.com/13283054/96118659-1ad26980-0eec-11eb-9ae6-bc91882d2dcf.png">

Finder does interestingly report the correct storage for it though, weird

**Comment by mbentley** [comment]
👍 ; would be curious if removing the max size on the share changes what Time Machine sees.

**Comment by JPyke3** [comment]
I think I am just going to throw this down to a bug with the latest Big Sur beta, I am getting this again:

![Screen Shot 2020-10-15 at 1 50 07 pm](https://user-images.githubusercontent.com/13283054/96119481-5883c200-0eed-11eb-9bb8-262796b65a11.png)

Time machine seems a bit buggy in Big Sur, as sometimes whenever I try to select the network drive, time machine thinks I am trying to backup the drive to itself:

![Screen Shot 2020-10-15 at 1 49 23 pm](https://user-images.githubusercontent.com/13283054/96119411-3c802080-0eed-11eb-8797-b260c2b4745c.png)

Might just camp on a new Big Sur release, see if it improves. At least after that command finder does pick up the SMB drive correctly, when I remove the max size from the storage, it just shows the entire size of the volume that the container is bound mounted to, which I believe is the intended behaviour.

**Comment by mbentley** [comment]
Well this certainly makes me glad I didn't just jump right in with the Big Sur beta :)

**Comment by JPyke3** [comment]
Bit of an update, new beta was seeded this morning, gave it a go just now. Can connect to the Drive a lot better now, but still won't start time machine, It just gets confused and tries to backup the internal disk to the internal disk.

**Comment by mbentley** [comment]
I wanted to circle back.  I just upgraded to Big Sur now that it is GA and Time Machine backups seem to be working as far as I can tell but please reopen if you have any issues.
