### ISSUE TITLE
Multiple user

### ISSUE THREAD

**Issue by gonzalocomas** [mbentley/docker-timemachine#58]
Thanks for this detailed docker.

I have a question, that I think is more Docker related than samba related.

I successfully managed to run your Docker (I tried one by one all smb methods). I want to implement a multiple user one. I had no problem adding a user via a .conf file. But I must be doing something wrong, because the sparsebundle is not stored in the share. I can access the share from the Mac (or from any computer on the network) but it seems the bundle is stored in a folder inside the Docker image and not on the host disk. As I said, I think this is something from Docker that I don't quite understand. If I use find command I can find the bundle in /var/lib/docker/overlay2/etc folder.

I will continue investigating how to set users correctly.

Regards

Gonzalo

**Comment by mbentley** [comment]
If you provide your run command and an example of your user config file, I can help.  If you're finding the sparse bundle in that directory, it's being stored in the copy on write file system so it won't persist outside of the container.  I would guess there is something bad in the config telling it to store data in the wrong place.

**Comment by gonzalocomas** [comment]
This is the run comand

sudo docker run -d --restart=always   --name timemachine   --network=macvlan1 --ip=10.0.1.250 -e CUSTOM_SMB_CONF="false"   -e CUSTOM_USER="false"   -e DEBUG_LEVEL="1"   -e MIMIC_MODEL="TimeCapsule8,119"   -e EXTERNAL_CONF="/users"   -e HIDE_SHARES="no"   -e TM_USERNAME="timemachine"   -e TM_GROUPNAME="timemachine"   -e TM_UID="1000"   -e TM_GID="1000"   -e PASSWORD="timemachine"   -e SET_PERMISSIONS="false"   -e SHARE_NAME="TimeMachine"   -e SMB_PORT="445"   -e VOLUME_SIZE_LIMIT="0"   -e WORKGROUP=“CASA”   -v /mnt/Seagate/timemachine:/opt/timemachine   -v timemachine-var-lib-samba:/var/lib/samba   -v timemachine-var-cache-samba:/var/cache/samba   -v timemachine-run-samba:/run/samba   -v /mnt/Seagate/timemachine-users:/users   mbentley/timemachine:smb


And this is the user I created

TM_USERNAME=gonzalocomas
TM_GROUPNAME=gonzalocomas
PASSWORD="mypassword"
SHARE_NAME=gonzalocomas
VOLUME_SIZE_LIMIT="2 T"
TM_UID=1001
TM_GID=1001

This file is stored in mnt/Seagate/timemachine-users (name gonzalocomas.conf)


If I run this I get a share named "gonzalocomas" and it says that is 2T in size. But is not "mapped" to /mnt/Seagate/timemachine.

And I can´t login using "timemachine" user. Only gonzalocomas.

**Comment by mbentley** [comment]
Ah, I see the problem.  My example isn't great and that causes confusion.  You will want to bind mount `/opt/gonzalocomas` from the container to your host.

So for each user, you will want to make sure that the value of `SHARE_NAME` is mounted from `/opt` in the container to somewhere on the host.  In your case from your example:

```
-v /mnt/Seagate/gonzalocomas:/opt/gonzalocomas \
```

I would also suggest setting:
```
-e SET_PERMISSIONS="true" \
```

Otherwise you will have to manually set the permissions on your host filesystem.

**Comment by mbentley** [comment]
Docs have been updated.  Let me know if you still have issues.

**Comment by gonzalocomas** [comment]
Thank you so much.

Everything is fine now.

Regards.

Gonzalo

**Comment by gonzalocomas** [comment]
Just a quick comment/question. If I don't use the macvlan the server
announces itself with the server name and in a Mac it shows a Timecapsule
icon. If I use macvlan the name of the server is a something like a hex
number and it changes every time I stop and start the container. (the icon
is the same one, a Timecapsule). This is not a problem, since I can access
the share directly with Cmd+K smb://ipadress of the container, but I don't
see where can I "name" the Docker server name.

And for the multiuser set up I ended up removing the part that refers to
the timemachine user, group and share. This is the run command:

sudo docker run -d --restart=always   --name timemachine
--network=macvlan1 --ip=10.0.1.250 -e CUSTOM_SMB_CONF="false"   -e
CUSTOM_USER="false"   -e DEBUG_LEVEL="1"   -e
MIMIC_MODEL="TimeCapsule8,119"   -e EXTERNAL_CONF="/users"   -e
HIDE_SHARES="true"    -e SET_PERMISSIONS="true"    -e SMB_PORT="445"    -e
WORKGROUP=“CASA”   -v timemachine-var-lib-samba:/var/lib/samba   -v
timemachine-var-cache-samba:/var/cache/samba   -v
timemachine-run-samba:/run/samba   -v /mnt/Seagate/timemachine-users:/users
-v /mnt/Seagate/timemachine/user1:/opt/user1 -v
/mnt/Seagate/timemachine/user2:/opt/user2 -v
/mnt/Seagate/timemachine/user3:/opt/user3 -v
/mnt/Seagate/timemachine/user4:/opt/user4 -v
/mnt/Seagate/timemachine/user5:/opt/user5  mbentley/timemachine:smb

Everything works great. Thanks again.

Gonzalo

**Comment by mbentley** [comment]
add `--hostname <whatever-hostname-you-want>`

**Comment by gonzalocomas** [comment]
OK. I thought that I had spotted all the differences. It was there, on the
first run command in your examples.

Thanks again.

Gonzalo.
