### ISSUE TITLE
Cannot connect TimeMachine

### ISSUE THREAD

**Issue by matteogatti** [mbentley/docker-timemachine#60]
I have a working container with samba service for local network storage. I use `dperson/samba` image with a basic configuration:
```
docker run -it --name samba -p 139:139 -p 445:445 \
  -v /srv/storage/shares/nas:/mount \
  -d -dit --restart unless-stopped dperson/samba -p \
  -u "user;password" \
  -s "public;/mount;yes;no;no;root" \
```
To configure time machine i had used the default configuration as showed in the README and creating a `macvlan`

```
docker network create -d macvlan --subnet=192.168.100.0/24 --gateway=192.168.100.1 -o parent=br0 macvlan1
```

```
docker run -d --restart=always \
  --network macvlan1 \
  --ip 192.168.100.230 \
  --name timemachine \
  --hostname timemachine \
  -p 137:137/udp \
  -p 138:138/udp \
  -p 139:139 \
  -p 445:445 \
  -e CUSTOM_SMB_CONF="false" \
  -e CUSTOM_USER="false" \
  -e DEBUG_LEVEL="1" \
  -e HIDE_SHARES="no" \
  -e EXTERNAL_CONF="" \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e TM_USERNAME="timemachine" \
  -e TM_GROUPNAME="timemachine" \
  -e TM_UID="1000" \
  -e TM_GID="1000" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="false" \
  -e SHARE_NAME="TimeMachine" \
  -e SMB_PORT="445" \
  -e VOLUME_SIZE_LIMIT="0" \
  -e WORKGROUP="WORKGROUP" \
  -v /srv/storage/shares/timemachine:/opt/timemachine \
  -v /srv/storage/samba/timemachine-var-lib-samba:/var/lib/samba \
  -v /srv/storage/samba/timemachine-var-cache-samba:/var/cache/samba \
  -v /srv/storage/samba/timemachine-run-samba:/run/samba \
  mbentley/timemachine:smb
```

The container startup without problems:
```
...
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 192.168.100.230 on eth0.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is timemachine.local. Local service cookie is 3895032456.
Service "timemachine" (/etc/avahi/services/smbd.service) successfully established.
```

But in finally i can't connect the service with the **Apple Time Machine** utility, i only see the samba service in the first container described above.

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                    PORTS                                                                    NAMES
c95a28845f32        mbentley/timemachine   "/entrypoint.sh s6-s…"   5 minutes ago       Up 5 minutes                                                                                       timemachine
7c1222ceaf0d        dperson/samba          "/sbin/tini -- /usr/…"   36 minutes ago      Up 36 minutes (healthy)   0.0.0.0:139->139/tcp, 137-138/udp, 0.0.0.0:445->445/tcp                  samba
```

**Comment by mbentley** [comment]
Just to start off with basics, I'm assuming that your local network is using 192.168.100.0/24 as well, correct?  Just making sure your network and macvlan work.  I haven't used macvlan on a bridge but from what I read, it should. 

How do you have your br0 interface configured?

Have you tried to manually connect to the share using Finder to see if it shows up there?

**Comment by matteogatti** [comment]
Thanks for the reply. 

> Just to start off with basics, I'm assuming that your local network is using 192.168.100.0/24 as well, correct? Just making sure your network and macvlan work. I haven't used macvlan on a bridge but from what I read, it should.
Yes, my network is 192.168.100.0/24 and, I forgot to tell you, the first implementation of the container was `mbentley/timemachine:afb` and its did works, or rather, the **Apple Time Machine** utility had discoverd the storage and had attached to it, but in really the backup didn't happen. 

> How do you have your br0 interface configured?
My doubt is about the bridge network, but `docker network create -d macvlan` command has run successfully.

> Have you tried to manually connect to the share using Finder to see if it shows up there?
In the same server were running docker there is also a container samba (as i told you) and if a try to connect my Mac in that server with the command `smb://192.168.100.230` i see the samba folders. While, before with the AFP image, the command `afp://192.168.100.230` did work well.

**Comment by mbentley** [comment]
Not the macvlan interface but the parent interface you're specifying - br0 on the host itself.

When you mention manually connecting to the Samba server via the IP, are you talking about connecting to the mbentley/timemachine container or dperson/samba?  It's not clear which one you're successfully connecting to as you mention the IP of 192.168.100.230.

Ignoring the other container as that one doesn't seem to be using macvlan, are you saying you can see the folders for both the afp and the smb based images?  Could you connect to the shares and drop files over on to them?

**Comment by matteogatti** [comment]
When i had used `mbentley/timemachine:afp` in my Mac I used to go on `Finder -> Go -> Connection to the server -> afp://192.168.100.230` and the share showed up on Finder. After that I opened the **Apple Time Machine** utility and connected the volume. But the problem was that utility don't save anything on it.

Now, following the same operation, but with `mbentley/timemachine:smb` container and using `smb://192.168.100.230` instead `afp://` the resource that will appear is the samba resource. And for answer to your question, yes I can save or deleter any thing I put on it.

I not specified you, but the ip `192.168.100.230` is the address of `br0` interface. I also tried to use another ip in the `docker run --network macvlan1 --ip 192.168.100.220` but it's unreachable. Maybe this is will be the problem, I need to use another ip different to the `br0` ip, but this doesn't connect with the interface?

**Comment by mbentley** [comment]
Ah ok. You need to specify a different IP when you use macvlan. Treat a container on macvlan the same as you would a VM or another machine on the network. You would not assign the same IP multiple times on your network. It should be another IP on the network that is available.

**Comment by mbentley** [comment]
I take it that providing a different IP worked? 🤞

**Comment by matteogatti** [comment]
Yes, I have setted up a new ip address, but for my mistake the bridged interface i need to use is `br3` and not `br0`. I'm was focused to a problem with `mavlan` and bridge interface configured under `netplan` and this led me astray.
