### ISSUE TITLE
rando hostname w/macvlan

### ISSUE THREAD

**Issue by tc60045** [mbentley/docker-timemachine#62]
Matt, stellar work here.  I've tried several of these through the years; yours was the first to run flawlessly and make me move to smb (inertia....)

To avoid contention with other docker stuff,  I created a new macvlan network per your instructions.  Worked perfectly.  Made docker-compose point to that network, and listed that network by its name as external.  All works -- can connect in Finder with the username / password.

Problem is this:  the hostname is now showing up on my network as the random Hexadecimal string Docker named my network:   8c16659497d3.   Shows up a server with that unfriendly name in Mac / Networking.   Looked all over for a way to change it, as it seems I need to tell avahi *not* to list it as that.   

Logs from docker-compose:

Attaching to timemachine
timemachine           | INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...
timemachine           | Creating /var/log/samba/cores
timemachine           | INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...
timemachine           | INFO: Avahi - adding the 'dk0', 'Veronica TM Server' share txt-record to /etc/avahi/services/smbd.service...
timemachine           | INFO: Group timemachine doesn't exist; creating...
timemachine           | INFO: User timemachine doesn't exist; creating...
timemachine           | INFO: Setting password from environment variable
timemachine           | chpasswd: password for 'timemachine' changed
timemachine           | INFO: INFO: CUSTOM_SMB_CONF=false; generating [Veronica TM Server] section of /etc/samba/smb.conf...
timemachine           | INFO: Samba - Created User timemachine password set to none.
timemachine           | INFO: Samba - Enabled user timemachine.
timemachine           | INFO: Samba - setting password
timemachine           | INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine
timemachine           | INFO: Avahi - completing the configuration in /etc/avahi/services/smbd.service...
timemachine           | INFO: entrypoint complete; executing 's6-svscan /etc/s6'
timemachine           | dbus socket not yet available; sleeping...
timemachine           | nmbd version 4.12.7 started.
timemachine           | Copyright Andrew Tridgell and the Samba Team 1992-2020
timemachine           | daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
timemachine           | smbd version 4.12.7 started.
timemachine           | Copyright Andrew Tridgell and the Samba Team 1992-2020
timemachine           | INFO: Profiling support unavailable in this build.
timemachine           | daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
timemachine           | Failed to fetch record!
timemachine           | Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
timemachine           | Successfully dropped root privileges.
timemachine           | avahi-daemon 0.8 starting up.
timemachine           | WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
timemachine           | Loading service file /etc/avahi/services/smbd.service.
timemachine           | Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.16.
timemachine           | New relevant interface eth0.IPv4 for mDNS.
timemachine           | Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
timemachine           | New relevant interface lo.IPv4 for mDNS.
timemachine           | Network interface enumeration completed.
timemachine           | Registering new address record for 192.168.1.16 on eth0.IPv4.
timemachine           | Registering new address record for 127.0.0.1 on lo.IPv4.
timemachine           | Server startup complete. Host name is 8c16659497d3.local. Local service cookie is 2675415000.
timemachine           | Service "8c16659497d3" (/etc/avahi/services/smbd.service) successfully established.

docker-compose.yml portion below:

      timemachine:
         container_name: timemachine
         networks: 
               - vero_macvlan
         environment:
           - IP=192.168.1.19                         # Matt - this doesn't work here; Docker Network (external) picks the IP
           - CUSTOM_SMB_CONF=false
           - CUSTOM_USER=false
           - LOG_LEVEL=info
           - EXTERNAL_CONF=
           - HIDE_SHARES=no
           - MIMIC_MODEL=TimeCapsule8,119
           - TM_USER=timemachine
           - TM_GROUPNAME=timemachine
           - TM_UID=1100
           - TM_GID=1100
           - PASSWORD=blahblahblah
           - SET_PERMISSIONS=false
           - SHARE_NAME=Veronica TM Server
           - SMB_PORT=445
           - VOLUME_SIZE_LIMIT=0
           - WORKGROUP=WORKGROUP
         restart: unless-stopped
         ports:
              - "137:137/udp"
              - "138:138/udp"
              - "139:139"
         volumes:
              - /tank1/timemachine:/opt/timemachine                  # previously existing backup area
              - /tank1/configs/tm_mb/timemachine-var-lib-samba:/var/lib/samba                 # note: I make configs available
              - /tank1/configs/tm_mb/timemachine-var-cache-samba:/var/cache/samba    #  to docker containers via a 
              - /tank1/configs/tm_mb/timemachine-run-samba:/run/samba                          # per-container directory on a zfs share
         ulimits:
              nofile:
                   soft: 65536
                   hard: 65536
         image: mbentley/timemachine:smb

Any tips on how to force Avahi / Docker to give the 'host' a proper host name?    Thanks!

**Comment by mbentley** [comment]
Sure, see https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir.  You need to tell Docker what hostname you want it to set.

**Comment by tc60045** [comment]
Yep, that will do it.   Thanks, Matt! 

For future reference, fellow users:   if you follow Matt's instructions in creating a macvlan, you may want to add "hostname: _________" to the TimeMachine service in docker-compose, so that the name that appears on your network is something recognizable and not a random, 16 character hexadecimal string.  Standard DNS rules apply for naming and thus Mac users, you cannot put a space in the hostname ("foo bar" will come through as foobar).  Dashes work.   Enjoy.

**Comment by harryohalloran** [comment]
@tc60045 , how did you setup the networks: section of your docker-compose.yml?  I've been trying to get mine working but I don't think I have it configured correctly.  I also don't want to conflict with my traefik proxy network running on there.

**Comment by balk77** [comment]
Thanks for clarifying! When not using docker-compose you can add `--hostname Timemachine` to the `docker run` command.
```
docker run -d --restart=always \
  --name timemachine \
  --network mynet \
  --ip 192.168.0.200 \
  --hostname Timemachine \
  -e CUSTOM_SMB_CONF="false" \
  -e CUSTOM_USER="false" \
etc
```
where `mynet` is my `macvlan` network
