### ISSUE TITLE
TM_USER vs. TM_USERNAME

### ISSUE THREAD

**Issue by tc60045** [mbentley/docker-timemachine#64]
Matt, my backup files were being created by user "1100," which is the UID of my already-created user, "timemachine." 

![by default 2020-11-11 at 1 24 05 PM](https://user-images.githubusercontent.com/2856318/98855190-36fcf400-2421-11eb-96c4-f1f746d45584.jpg)

That led me to spot a potential inconsistency.  It appears that in entrypoint.sh, line 11, you are using "TM_USERNAME":  

#!/bin/sh

# set default values
LOG_LEVEL="${LOG_LEVEL:-info}"
SET_PERMISSIONS="${SET_PERMISSIONS:-false}"
SHARE_NAME="${SHARE_NAME:-TimeMachine}"
CUSTOM_AFP_CONF="${CUSTOM_AFP_CONF:-false}"
CUSTOM_SMB_CONF="${CUSTOM_SMB_CONF:-false}"
SMB_PORT="${SMB_PORT:-445}"
CUSTOM_USER="${CUSTOM_USER:-false}"
TM_USERNAME="${TM_USERNAME:-timemachine}"
TM_GROUPNAME="${TM_GROUPNAME:-timemachine}"
TM_UID="${TM_UID:-1000}"
TM_GID="${TM_GID:-${TM_UID}}"
VOLUME_SIZE_LIMIT="${VOLUME_SIZE_LIMIT:-0}"
WORKGROUP="${WORKGROUP:-WORKGROUP}"
EXTERNAL_CONF="${EXTERNAL_CONF:-}"
HIDE_SHARES="${HIDE_SHARES:-no}" 

However in the stock smb docker-compose, you set the environment variable as TM_USER.

version: "3.7"
services:
  timemachine:
    network_mode: "host"
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - LOG_LEVEL=info
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USER=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - SMB_PORT=445
      - VOLUME_SIZE_LIMIT=0
      - WORKGROUP=WORKGROUP

I suspect the environment variable in docker-compose should in fact be TM_USERNAME but want to confirm with you before I mess something up.  

Thanks!

**Comment by mbentley** [comment]
You're correct, it should be `TM_USERNAME` not `TM_USER`.  I just merged a PR to fix the example.  Thanks for reporting!
