### ISSUE TITLE
Raspberry writeup

### ISSUE THREAD

**Issue by HofmannZ** [mbentley/docker-timemachine#68]
I did not see any references to any raspberry writeups.

If there are any I would love to know, and so would a load of other people I recon. ;-)

**Comment by mbentley** [comment]
Just curious, what specifically are you looking for in regards to any sort of writeup?  More than just running the container?  Any other specifics?

**Comment by HofmannZ** [comment]
Yeah, just a getting started guide, for those that don't have the time to dive in completely ;)

**Comment by mbentley** [comment]
If someone has the time to write it up, I'm all for it but I currently don't.
