### ISSUE TITLE
Big Sur changes to Time Machine causing permissions error on first backup

### ISSUE THREAD

**Issue by melyux** [mbentley/docker-timemachine#69]
Getting a "permission denied" error when trying to create a backup for the first time from Big Sur. Looks like this is a common problem caused by Apple changing something without telling anyone, and seems to be fixed by adding some options to the `smb.conf`, apparently the most central being adding `acl_xattr` to `vfs objects =`. Check out https://developer.apple.com/forums/thread/666293

Adding `catia` to `vfs objects` may be a good idea too, I keep seeing it everywhere for Time Machine purposes:

> As an inheritance from Windows some characters (such as the colon :) are illegal in SMB, while they are allowed on both macOS and Linux. This means that in order to transfer them over SMB they need to be encoded somehow, and Time Machine uses a private Unicode range for this. This is totally fine, but can (allegedly) look a bit weird if listing the files on the server. So, optionally the catia module can be used to reverse this encoding server side.

But that may come with other strings attached (some say you also have to add `fruit:encoding = native` when you use it?), and it's irrelevant for this issue, I think.

**Comment by mbentley** [comment]
Thanks for reporting.  I've seen conflicting information about `catia` as I actually removed it relatively recently via https://github.com/mbentley/docker-timemachine/commit/028d0e704edd7025ce4fe3a4fd7561db9abe6240 based on the [Samba wiki](https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X).  I didn't have any issues when `catia` was included or excluded, at least with an existing time machine backup.

I just created #70 which allows you to set variables to customize the values mentioned.  I created and pushed a docker image to test: `mbentley/timemachine:smb-pr70`.  There are three new variables that default to the following values which you can customize to change the settings as needed:

```
  -e SMB_INHERIT_PERMISSIONS="no" \
  -e SMB_NFS_ACES="yes" \
  -e SMB_VFS_OBJECTS="fruit streams_xattr" \
```

If you could, give that a shot and let me know if that works for you.  I can add a variable for `fruit:encoding` but there are  potential issues with adding it if users try to change it without understanding the impact of doing so.  Per the [Samba docs on vfs_fruit](https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html):

> fruit:encoding = [ native | private ]
> Controls how the set of illegal NTFS ASCII character, commonly used by OS X clients, are stored in the filesystem.
> 
> Important: this is known to not fully work with fruit:metadata=stream or fruit:resource=stream.
> 
> private (default) - store characters as encoded by the OS X client: mapped to the Unicode private range
> 
> native - store characters with their native ASCII value. Important: this option requires the use of vfs_catia in the VFS module stack as shown in the examples section.

**Comment by melyux** [comment]
Just tried adding those settings `xcl_attr` and it worked. I was able to create a new backup on Big Sur. The number of people both using this docker and backing up for the very first time are probably low right now, but if other people start having this problem as they probably will, you may have to make those 3 things the defaults.

**Comment by mbentley** [comment]
Thanks for reporting back, much appreciated. So it was `xcl_attr` that you added and not `acl_xattr`?  Could you confirm?

**Comment by melyux** [comment]
Total typo. It was `acl_xattr`

**Comment by harryohalloran** [comment]
I'm having the same issue with my instance.  I just moved over to the SMB version (which it looks like I got working on a host with another SMB service already running) but can't create a new backup with my Mac mini running Big Sur.  My MacBook Air with an existing backup works fine.  I did try adding both acl_xaatr and catia to the vfs objects but that doesn't solve the problem.  Let me know if you guys can get it working.

**Comment by melyux** [comment]
Was it `acl_xattr` you added? `SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr` to be exact? Or was it the misspelled “acl_xaatr” like you wrote? What a mess of a parameter name...

What’s the error you’re getting in console/TM itself when it fails?

**Comment by harryohalloran** [comment]
I have it currently set as:       - SMB_VFS_OBJECTS=acl_xattr catia fruit streams_xattr
I also had tried:       - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
Here's the error I'm getting on the Mac 

Failed to create '/Volumes/.timemachine/timemachine._smb._tcp.local./4B5ABF62-E8B2-4A6E-ACBC-25D5D9698F12/TimeMachine/9890CEDC-B158-5E99-BFB4-BEF00E63C30F.sparsebundle', results: {
}, error: 13 Permission denied

Here's my current environment section (note, I've tried inheriting permissions too)
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - DEBUG_LEVEL=2
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule9,119
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=${PUID}
      - TM_GID=${PGID}
#      - PASSWORD_FILE=/run/secrets/password
      # or
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - SMB_INHERIT_PERMISSIONS=no
      - SMB_NFS_ACES=no
      - SMB_PORT=445
      - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
      - VOLUME_SIZE_LIMIT="4 T"
      - WORKGROUP=WORKGROUP

**Comment by melyux** [comment]
Do this and let me know what happens: set SMB_INHERIT_PERMISSIONS to yes, and delete the .sparsebundle the backup attempt created in the SMB share. Then try the backup again.

**Comment by harryohalloran** [comment]
Changed SMB_INHERIT_PERMISSIONS to yes, deleted the sparse bundle, and then tried again.  Got the same error (actually tried on another new MacBook Air on Big Sur and am having the same issue): Failed to create '/Volumes/.timemachine/timemachine._smb._tcp.local./C2982B94-41B6-42BD-A6E1-08E863B01C8D/TimeMachine/1989F697-A19A-51DE-A1D1-518689ABEE90.sparsebundle', results: {
}, error: 13 Permission denied

I'm also getting some exceptions around the failure (see screenshot) 
<img width="1257" alt="Screen Shot 2020-11-24 at 7 20 32 PM" src="https://user-images.githubusercontent.com/7769053/100169898-20778380-2e8a-11eb-9abb-708c728bb134.png">

**Comment by mbentley** [comment]
Are the permissions set correctly for your persistent data directory so that the UID/GID of the `timemachine` user that is created has the right ownership (e.g. - have you tried using `SET_PERMISSIONS=true`)?

I really need to get another mac to be able to test new backups.

**Comment by harryohalloran** [comment]
Yep, tried setting it to true as well with the same result.  I actually have a number of Macs to test with a full house and two are working fine using the same container.  Here are the test cases:

1. MacBook Air running High Sierra - No prior backup - Needs to create new backup file - Pass
2. MacBook Air running El Capitan - Prior backup - Appends existing backup file - Pass
3. Brand new MacBook Air running Big Sur - No prior backup - Needs to create new backup file - Fail
4. Mac mini running Big Sur - No prior backup  - Needs to create new backup file - Fail

**Comment by melyux** [comment]
Could you post the smb.conf file from inside the container?

**Comment by harryohalloran** [comment]
`[global]              
   min protocol = SMB2            
   server role = standalone server
   workgroup = WORKGROUP
   smb ports = 445          
   #unix password sync = yes       
   log file = /var/log/samba/log.%m
   logging = file     
   max log size = 1000
   security = user   
   load printers = no          
   access based share enum = no
   hide unreadable = no             
   vfs objects = fruit streams_xattr
   fruit:delete_empty_adfiles = yes
   fruit:metadata = stream       
   fruit:model = TimeCapsule9,119
   fruit:posix_rename = yes   
   fruit:veto_appledouble = no                    
   fruit:wipe_intentionally_left_blank_rfork = yes
             
[TimeMachine]      
   fruit:aapl = yes        
   fruit:time machine = yes           
   fruit:time machine max size = "4 T"
   path = /opt/timemachine  
   valid users = timemachine
   browseable = yes
   writable = yes
   vfs objects = fruit streams_xattra`

**Comment by mbentley** [comment]
What is the filesystem of your persistent data disk?

**Comment by harryohalloran** [comment]
Ext4

**Comment by mbentley** [comment]
Quick reply :) I'm also assuming that the above output of smb.conf is with the default settings and no customizations to vfs objects, right?

**Comment by harryohalloran** [comment]
Here's what I have set:       - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr

**Comment by mbentley** [comment]
Ok then the settings aren't applying. Make sure you've pulled the latest image.

**Comment by mbentley** [comment]
If it is working as expected, you should see the `vfs objects` lines show up as:

```
vfs objects = acl_xattr fruit streams_xattr
```

**Comment by harryohalloran** [comment]
Thanks, after all of that, it looks like it wasn't pulling the latest even though that's how I had it tagged in my docker-compose file.  I manually removed the container and the old images and then repulled and as of this morning, things seem to be working.  It did, however, take a long time to go from preparing to actually backing up (I went to bed before it started backing up so saw it actually worked this morning and still has some time to go).  This seems way slower than normal so I'll have to figure out what's going on there but things seem to be moving in the right direction.  Thanks again.

**Comment by mbentley** [comment]
Good deal.  I've found that initial backups are very problematic and slow.  There is some throttling that occurs but there is a parameter that can be tweaked which I hear should make it faster: https://www.imore.com/how-speed-your-time-machine-backups

I'll submit a PR to change the default settings so that it adds `acl_xattr` by default.  Thanks!
