### ISSUE TITLE
Latest armv7l docker image is broken

### ISSUE THREAD

**Issue by steveh80** [mbentley/docker-timemachine#77]
After upgrading to the latest armv7l docker image the service doesn't come up again.

docker logs keeps posting the following output:

```
s6-supervise avahi: warning: can't happen: timeout while the service is up!
s6-supervise dbus: warning: can't happen: timeout while the service is up!
s6-supervise nmbd: warning: can't happen: timeout while the service is up!
s6-supervise avahi: warning: can't happen: timeout while the service is up!
s6-supervise smbd: warning: can't happen: timeout while the service is up!
s6-supervise dbus: warning: can't happen: timeout while the service is up!
s6-supervise nmbd: warning: can't happen: timeout while the service is up!
s6-supervise smbd: warning: can't happen: timeout while the service is up!
s6-supervise avahi: warning: can't happen: timeout while the service is up!
```

**Comment by steveh80** [comment]
I already talked to Matt and he pushed a temporary image with the previous version which is available with the tag ```mbentley/timemachine:smb-armv7l```

**Comment by mbentley** [comment]
In additional, I also changed the default image tag to `alpine:3.12` for now.  I filed an issue with Alpine Linux - https://gitlab.alpinelinux.org/alpine/aports/-/issues/12346

I found a similar issue in another project: https://github.com/HenryQW/Awesome-TTRSS/issues/240

**Comment by steveh80** [comment]
Very good, thanks so much!

**Comment by mbentley** [comment]
The fix is now in `edge`, not yet released: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12346#note_142857

I will update the Dockerfile when it makes its way past edge.

**Comment by mbentley** [comment]
The release of Alpine 3.14 was [just announced](https://alpinelinux.org/posts/Alpine-3.14.0-released.html).  Waiting on the images to be available.  I manually tested by upgrading the packages in an armv7l image and it works flawlessly on 3.14.  Will merge https://github.com/mbentley/docker-timemachine/pull/91 to fix this as soon as the image on Docker Hub gets updated.
