### ISSUE TITLE
Time Machine can't connect to backup disk when starting second backup

### ISSUE THREAD

**Issue by awaisas** [mbentley/docker-timemachine#89]
Hi,

First of all thanks for an awesome docker image. Using the docs I have been able to run the first Mac backup successfully where the server is a Raspberry Pi running dietpi OS. I have used encrypt disk option in Time Machine. Now, when I retry to do a backup I get the error "Time Machine can't connect to backup disk". However, if I recreate an empty backup folder on the host and restart the docker container I am still again able to do my first backup. I thought maybe it is due to file permissions, however I can browse the files both from host and container and in addition create files which appear both inside and outside the container. 

```
$id dietpi
uid=1000(dietpi) gid=1000(dietpi)

```
Output:

**in the host:**
$ ls -l

```
total 208
-rwxrwxr-x+ 1 dietpi dietpi    500 Apr 10 12:02 Info.bckup
-rwxrwxr-x+ 1 dietpi dietpi    500 Apr 10 12:02 Info.plist
drwxrwsr-x+ 2 dietpi dietpi  69632 Apr 10 18:02 bands
-rwxrwxr-x+ 1 dietpi dietpi    516 Apr 10 12:04 com.apple.TimeMachine.MachineID.bckup
-rwxrwxr-x+ 1 dietpi dietpi    516 Apr 10 12:04 com.apple.TimeMachine.MachineID.plist
-rwxrwxr-x+ 1 dietpi dietpi   1094 Apr 10 18:02 com.apple.TimeMachine.Results.plist
-rwxrwxr-x+ 1 dietpi dietpi    430 Apr 10 18:02 com.apple.TimeMachine.SnapshotHistory.plist
drwxrwsr-x+ 2 dietpi dietpi  69632 Apr 10 18:02 mapped
-rwxrwxr-x+ 1 dietpi dietpi 122368 Apr 10 12:02 token
```

**in the container:**
```
$ ls -l
total 208
-rwxrwxr-x    1 timemach timemach       500 Apr 10 10:02 Info.bckup
-rwxrwxr-x    1 timemach timemach       500 Apr 10 10:02 Info.plist
drwxrwsr-x    2 timemach timemach     69632 Apr 10 16:02 bands
-rwxrwxr-x    1 timemach timemach       516 Apr 10 10:04 com.apple.TimeMachine.MachineID.bckup
-rwxrwxr-x    1 timemach timemach       516 Apr 10 10:04 com.apple.TimeMachine.MachineID.plist
-rwxrwxr-x    1 timemach timemach      1094 Apr 10 16:02 com.apple.TimeMachine.Results.plist
-rwxrwxr-x    1 timemach timemach       430 Apr 10 16:02 com.apple.TimeMachine.SnapshotHistory.plist
drwxrwsr-x    2 timemach timemach     69632 Apr 10 16:02 mapped
-rwxrwxr-x    1 timemach timemach    122368 Apr 10 10:02 token
```

**Comment by mundschenk-at** [comment]
I've noticed the same issue, what was the type or what did fix things for you?

**Comment by awaisas** [comment]
In my case it was sufficient to reset VOLUME_SIZE_LIMIT="0" again. To make sure there's no error in the docker container setup, you could try to recreate a container with minimal changes in the variables.

**Comment by mundschenk-at** [comment]
Strangely, the disk was found on a second try. No idea why macOS could not connect the two times.
