### ISSUE TITLE
add additional shares

### ISSUE THREAD

**Issue by utdrmac** [mbentley/docker-timemachine#9]
Would be nice to see `/etc/netatalk/afp.conf` mountable/overridden from host so that additional shares could be added.

On my old NAS, it used an `include =` to add additional shares. Maybe this could be an easy way for users to add. Leave the default afp.conf as-is, but add an additional `shares.conf` which is empty by default, but user could do `-v /path/shares.conf:/etc/netatalk/shares.conf` for extras.

Thoughts?

**Comment by mbentley** [comment]
@utdrmac - I think that's reasonable.  I could either go with a flag to allow you to provide your own complete file or I could allow a user to put their own file(s) via bind mount and make it so that the entrypoint simply appends them to the `afp.conf` at run time when it is generated.  What do you think would be easiest from a user perspective?

**Comment by utdrmac** [comment]
This is another netatalk docker I tried using yesterday because it allows you to override the afp.conf with a host mount. https://github.com/kjake/docker-netatalk

```
docker run -d --restart always \
  --name timemachine --net=host \
  -v /opt/timemachine/afp.conf:/etc/afp.conf \
  -v /opt/media:/media/share \
  -v /opt/timemachine:/media/timemachine \
  -e AFP_USER=timeuser -e AFP_PASSWORD=timeuser1 \
  -e AFP_UID=1000 -e AFP_GID=1000 \
  kjake/netatalk
```

I think overriding afp.conf would be easiest and most flexible. If you went the additional/include option, then you can't override any `[Global]` settings if you wanted.

I was going to stick with kjake's container, but I've been unsuccessful in getting avahi to work properly when ran on the host. I can't get timemachine to see the mount. If I stop avahi on host, and use your container, TM/avahi works just fine, but I don't have the extra share that I'd like to see.

**Comment by mbentley** [comment]
See #10.  I haven't been able to test it yet at the moment because I'm on a plane.

**Comment by utdrmac** [comment]
#10 looks good to me.

**Comment by mbentley** [comment]
I did a quick via ssh; made some minor changes but was overall looking like it was working correctly.  Let me know if you have any issues once the image [autobuilds on hub](https://hub.docker.com/r/mbentley/timemachine/tags).
