### ISSUE TITLE
Trouble Connecting via MacVlan

### ISSUE THREAD

**Issue by ootoovak** [mbentley/docker-timemachine#93]
**Describe the bug**
Following the instructions to get the Docker image up with Docker Compose and MacVlan I have had trouble connecting to the timemachine container even though it shows up on the network with Avahi. The host system is running both Avahi and Samba so I must use the MacVlan approach.

**To Reproduce**
On a machine that is:
```
Linux 5.10.43-rockchip64 aarch64
Armbian 21.05.6 Focal
Docker version 20.10.7
docker-compose version 1.29.2
```

With a physical network of:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.86.100  netmask 255.255.255.0  broadcast 192.168.86.255
```

Docker compose setup:
```
    timemachine:
        container_name: timemachine
        image: mbentley/timemachine:smb
        restart: always
        hostname: timemachine
        networks:
            timemachine:
                ipv4_address: 192.168.86.25
        environment:
            - PASSWORD='Example-N3w-Password'
        volumes:
            - /media/internal-hd/timemachine:/opt/timemachine
            - timemachine-var-lib-samba:/var/lib/samba
            - timemachine-var-cache-samba:/var/cache/samba
            - timemachine-run-samba:/run/samba

volumes:
    timemachine-var-lib-samba:
    timemachine-var-cache-samba:
    timemachine-run-samba:

networks:
    timemachine:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.86.100/24
                  ip_range: 192.168.86.0/24
                  gateway: 192.168.86.1
```

At first I could see the `timemachine` appear from my Mac laptop Finder network explorer and Time Machine from System Preferences. But when I tried to connect it would fail (almost like a time out?). I then found [this article](https://collabnix.com/2-minutes-to-docker-macvlan-networking-a-beginners-guide/) and the last step of doing:

```
sudo ip link add mac0 link eth0 type macvlan mode bridge
sudo ip addr add 192.168.86.100/24 dev mac0
sudo ifconfig mac0 up
```

Seemed to help. I would then at least connect to the `timemachine` container and ask for authentication but neither the default or custom password worked to connect.

**Expected behavior**
I expected my Docker Compose setup would allow me to have the network auto discovery working while keeping the host running Samba and Avahi but it doesn't seem to, or requires some manual steps after Docker Compose has set up the containers.

Even then it still doesn't seem to work past auth for some reason.

**How you're launching your container**
Docker Compose, see above.

**Container Logs**
```
INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...,
INFO: Creating /var/log/samba/cores,
INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...,
INFO: Avahi - adding the 'dk0', 'TimeMachine' share txt-record to /etc/avahi/services/smbd.service...,
INFO: Group timemachine doesn't exist; creating...,
INFO: User timemachine doesn't exist; creating...,
INFO: Setting password from environment variable,
chpasswd: password for 'timemachine' changed,
INFO: INFO: CUSTOM_SMB_CONF=false; generating [TimeMachine] section of /etc/samba/smb.conf...,
INFO: Samba - Created User timemachine password set to none.,
INFO: Samba - Enabled user timemachine.,
INFO: Samba - setting password,
INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine,
INFO: Avahi - completing the configuration in /etc/avahi/services/smbd.service...,
INFO: running test for xattr support on your time machine persistent storage location...,
INFO: xattr test successful - your persistent data store supports xattrs,
INFO: entrypoint complete; executing 's6-svscan /etc/s6',
dbus socket not yet available; sleeping...,
nmbd version 4.14.5 started.,
Copyright Andrew Tridgell and the Samba Team 1992-2021,
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections,
smbd version 4.14.5 started.,
Copyright Andrew Tridgell and the Samba Team 1992-2021,
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).,
Successfully dropped root privileges.,
avahi-daemon 0.8 starting up.,
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!,
Loading service file /etc/avahi/services/smbd.service.,
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.86.25.,
New relevant interface eth0.IPv4 for mDNS.,
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.,
New relevant interface lo.IPv4 for mDNS.,
Network interface enumeration completed.,
Registering new address record for 192.168.86.25 on eth0.IPv4.,
Registering new address record for 127.0.0.1 on lo.IPv4.,
INFO: Profiling support unavailable in this build.,
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections,
Failed to fetch record!,
Server startup complete. Host name is timemachine.local. Local service cookie is 3899302232.,
Service "timemachine" (/etc/avahi/services/smbd.service) successfully established.
```

**Additional context**
Added as much context as I could think of above.

Thanks in advance for any help and thanks for making yourself available to answer these types of questions! Much appreciated.

**Comment by mbentley** [comment]
Your time machine container needs to use an unused IP address, not the IP of your container machine host.  Think of a macvlan container as just another machine on your network.

**Comment by ootoovak** [comment]
@mbentley do you mean where I wrote the `subnet: 192.168.86.100/24` for the subnet or do you mean for the command `sudo ip addr add 192.168.86.100/24 dev mac0`?

Because I'm pretty sure I tried with a subnet of `subnet: 192.168.86.1/24` and it didn't work. But maybe this should be the IP I want like `subnet: 192.168.86.25/24`? In any case I'll try both and see what works.

If you are talking about `sudo ip addr add 192.168.86.100/24 dev mac0` command I don't remember what I tried but I can try the IP address I intend for the container of `sudo ip addr add 192.168.86.25/24 dev mac0` but I'll wait and try the above fixes first as I don't know how to reverse these commands yet if I get it wrong. 😅 

Thanks again.

**Comment by mbentley** [comment]
In your compose file for the container:

`ipv4_address: 192.168.86.25`

That IP matches your host; it should be unique on your network.  Your subnets should match your physical subnets so that should be correct.

**Comment by ootoovak** [comment]
Ah! I didn't even notice that bit! I was looking at the `inet 192.168.86.100` part not the `broadcast 192.168.86.25`. I will try a different IP address.
````
inet 192.168.86.100  netmask 255.255.255.0  broadcast 192.168.86.25
```

**Comment by ootoovak** [comment]
Which I actually entered wrong above (and have now amended). I missed the trailing `5` off of it before. The broadcast actually ends in `255` not `25`.

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.86.100  netmask 255.255.255.0  broadcast 192.168.86.255
```

**Comment by ootoovak** [comment]
Ok I've changed my `docker-compose.yml` config to this and I'm still having issues connecting.
```
    timemachine:
        container_name: timemachine
        image: mbentley/timemachine:smb
        restart: always
        hostname: timemachine
        networks:
            timemachine:
                ipv4_address: 192.168.86.123
        environment:
            - PASSWORD='Example-N3w-Password'
        volumes:
            - /media/internal-hd/timemachine:/opt/timemachine
            - timemachine-var-lib-samba:/var/lib/samba
            - timemachine-var-cache-samba:/var/cache/samba
            - timemachine-run-samba:/run/samba

volumes:
    timemachine-var-lib-samba:
    timemachine-var-cache-samba:
    timemachine-run-samba:

networks:
    timemachine:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.86.100/24
                  ip_range: 192.168.86.0/24
                  gateway: 192.168.86.1
```

**Comment by ootoovak** [comment]
I can't ping `192.168.86.123` from my laptop but I'm not sure if should be able to. My laptop can see it on the network but can't connect to it.
![Untitled](https://user-images.githubusercontent.com/105251/126083087-1a9b9690-745c-4618-8b7d-f9e30893b8fe.jpg)
![Untitled2](https://user-images.githubusercontent.com/105251/126083090-e28e7cd9-31de-4992-baaf-ed172ab929ab.jpg)

**Comment by ootoovak** [comment]
Most recent logs from the container:
```
INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...,
INFO: Creating /var/log/samba/cores,
INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...,
INFO: Avahi - adding the 'dk0', 'TimeMachine' share txt-record to /etc/avahi/services/smbd.service...,
INFO: Group timemachine doesn't exist; creating...,
INFO: User timemachine doesn't exist; creating...,
INFO: Setting password from environment variable,
chpasswd: password for 'timemachine' changed,
INFO: INFO: CUSTOM_SMB_CONF=false; generating [TimeMachine] section of /etc/samba/smb.conf...,
INFO: Samba - Created User timemachine password set to none.,
INFO: Samba - Enabled user timemachine.,
INFO: Samba - setting password,
INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine,
INFO: Avahi - completing the configuration in /etc/avahi/services/smbd.service...,
INFO: running test for xattr support on your time machine persistent storage location...,
INFO: xattr test successful - your persistent data store supports xattrs,
INFO: entrypoint complete; executing 's6-svscan /etc/s6',
dbus socket not yet available; sleeping...,
nmbd version 4.14.5 started.,
Copyright Andrew Tridgell and the Samba Team 1992-2021,
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections,
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).,
Successfully dropped root privileges.,
avahi-daemon 0.8 starting up.,
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!,
Loading service file /etc/avahi/services/smbd.service.,
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.86.123.,
New relevant interface eth0.IPv4 for mDNS.,
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.,
New relevant interface lo.IPv4 for mDNS.,
Network interface enumeration completed.,
Registering new address record for 192.168.86.123 on eth0.IPv4.,
Registering new address record for 127.0.0.1 on lo.IPv4.,
smbd version 4.14.5 started.,
Copyright Andrew Tridgell and the Samba Team 1992-2021,
INFO: Profiling support unavailable in this build.,
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections,
Failed to fetch record!,
Server startup complete. Host name is timemachine.local. Local service cookie is 3733336004.,
Service "timemachine" (/etc/avahi/services/smbd.service) successfully established.
```

**Comment by mbentley** [comment]
The only thing that I see that might be off is the `subnet` config for your macvlan network.  I am not sure if Docker is smart enough to figure out the appropriate configuration but try changing your network configuration from this:

```
networks:
    timemachine:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.86.100/24
                  ip_range: 192.168.86.0/24
                  gateway: 192.168.86.1
```

To this:

```
networks:
    timemachine:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.86.0/24
                  ip_range: 192.168.86.0/24
                  gateway: 192.168.86.1
```

Basically, just updating the subnet range from `192.168.86.100/24` to `192.168.86.0/24`.

Just for reference, here is my equivalent command using `docker network create...`:

```
docker network create -d macvlan --subnet=192.168.0.0/22 --gateway=192.168.0.1 -o parent=ens7f1 macvlan1
```

The `ip link` commands should only really be needed if you need to have the container communicate with the container host since by default macvlan doesn't allow communication back to the IP on the interface of which macvlan is using but that should be irrelevant for what you're trying to do.

**Comment by ootoovak** [comment]
@mbentley sorry it has taken me a little while to get back to you. Sadly, changing the subnet how you mentioned didn't work for me. I may have to fall back to the without-Avahi version.

That said because the `timemachine` does show up on my network, I wonder if it is some kind of drive permissions issue. I am running Ubuntu on a SoC board and using an SATA drive for these backups. I seem to be having some permission issues on another drive that docker uses so maybe it is a similar issue. While I've not explicitly declared them in my Docker Compose file I have confirmed that the default `TM_UID="1000"` and `TM_GID="1000"` are correct using `id $user`.

If I figure anything out I'll report back here. :)

**Comment by ootoovak** [comment]
Andy idea if the `Failed to fetch record!,` line might be a reason why I'm failing to connect the broadcasted `timemachine` instance? Also, any tips on how I might start troubleshooting this would be aces if you have any ideas. Thanks!
```
Registering new address record for 127.0.0.1 on lo.IPv4.,
Registering new address record for 192.168.86.111 on eth0.IPv4.,
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections,
Failed to fetch record!,
Server startup complete. Host name is timemachine.local. Local service cookie is 3481588932.,
Service "timemachine" (/etc/avahi/services/smbd.service) successfully established.
```

**Comment by mbentley** [comment]
Sorry for the delayed response.  The `Failed to fetch record!` message is actually normal to see.  Setting `DEBUG_LEVEL` to `3`, which puts the services in debug, might expose something that is not being shown in normal log levels.

If you haven't already tried to get rid of the `mac0` bridge, I would try that as that really shouldn't be necessary from an external machine on the network.

Besides that, checking out the logs from a mac in the `Console` app to look for anything suspicious while it is trying to connect would be the other route.  Have you been successfully able to map to the Samba share using Finder or not?  That part wasn't clear to me as that would be another debugging step.

**Comment by ootoovak** [comment]
Thanks again @mbentley, and no worries, I have not expectations about you providing support! I appreciate you have been kind enough to do so in your free time so thank you.

I have not been able to to map the Samba share using Finder. I'll try the debugging options you have suggested sometime soon and I'll see if I can find out a bit more about what is going on.

**Comment by nov1n** [comment]
@ootoovak Did you ever figure this one out? I'm running into the same problem.

**Comment by ootoovak** [comment]
@nov1n no I never did. After trying a few configurations I gave up, then got busy with other things. If you ever get it working I'd be interested to hear how. 🙂

**Comment by nov1n** [comment]
So in my case the problem was that my parent interface is `wlan0` and macvlan does not support wireless interfaces. I changed to `ipvlan` and now it works without any problems. Maybe this is something you could try?

@mbentley maybe this is something to add to the readme? It's not at all clear from macvlan docs that wireless interfaces are unsupported.
