### ISSUE TITLE
Is it possible to run two drives at the same time, one for backup and one for storage

### ISSUE THREAD

**Issue by reqyo** [mbentley/docker-timemachine#96]
I'm just curious if this is possible with this container, is there a way where when I click on my local network to see the time capsule, could there be 2 or 3 drives there, and specify space for each one in that way. Forgive me if you can already do this, I'm currently unsure of how to do it!

Thanks!

**Comment by mbentley** [comment]
Yes - two different users with two bind mounts.
e.g. - user1 and user2 which would be `/opt/user1` and `/opt/user2`. Bind mount each path uniquely to a different drive.

**Comment by reqyo** [comment]
Thank you!

**Comment by reqyo** [comment]
Hey man, I tried this again the other day, as I wanted to get a new hard drive to do this, Im still having trouble with the command, what I essentially want is one user, that has access to two directories on the same disk that both have different sizes. Have you got an example command because Im pretty sure im doing this incorrectly. Thank you

**Comment by mbentley** [comment]
This image will not currently do that without applying a custom configuration with the `CUSTOM_SMB_CONF` option.  You should be able to specifically set a user, run the container, copy out the `smb.conf` using `docker cp...` and then use the option for a custom config to create the 2nd share.  Directly having this sort of configuration out of the box is out of scope for the image just from a standpoint of trying to wrangle the existing spaghetti entrypoint script as it stands.
