### ISSUE TITLE
Disk is not seen when M1 MacBook wakes up

### ISSUE THREAD

**Issue by justinglock40** [mbentley/docker-timemachine#97]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/23133649/128648580-fd5e7569-4266-4949-ae9b-9e1f6ab9bd16.png">

Happens every time the computer has been sleep for some period of time. When you press use this is the Time Machine remakes the initial back-up again.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/23133649/128648618-a5b091c2-a075-4e70-aedf-3cfc80bcb996.png">

**Comment by mbentley** [comment]
I can’t help without any details at all.  How are you running the container?  Full run command or compose file without passwords would be ideal, full debug log output, setting log level to 3 will give debug logs as well which may show more detail.
